--
-- PostgreSQL database dump
--

-- Dumped from database version 14.12 (Ubuntu 14.12-0ubuntu0.22.04.1)
-- Dumped by pg_dump version 14.12 (Ubuntu 14.12-0ubuntu0.22.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: catalogo; Type: TABLE; Schema: public; Owner: joacoeze
--

CREATE TABLE public.catalogo (
    id integer NOT NULL,
    nombre_de_pelicula character varying(100),
    url_imagen character varying(400),
    "año_de_estreno" integer,
    genero character varying(100),
    duracion integer,
    sinopsis character varying(1000),
    director character varying(200),
    actores_principales text,
    productora character varying(100),
    pais_de_origen character varying(100),
    puntaje_segun_critica numeric(2,1),
    url_trailer text
);


ALTER TABLE public.catalogo OWNER TO joacoeze;

--
-- Data for Name: catalogo; Type: TABLE DATA; Schema: public; Owner: joacoeze
--

COPY public.catalogo (id, nombre_de_pelicula, url_imagen, "año_de_estreno", genero, duracion, sinopsis, director, actores_principales, productora, pais_de_origen, puntaje_segun_critica, url_trailer) FROM stdin;
2	The Batman	https://comicparatodos.wordpress.com/wp-content/uploads/2022/03/the-batman.jpg	2022	Accion, Crimen, Suspenso, y Superheroes.	176	En su segundo año luchando contra el crimen, Batman explora la corrupción existente en la ciudad de Gotham y el vínculo de esta con su propia familia. Además, entrará en conflicto con un asesino en serie conocido como "el Acertijo".	Matt Reeves	Robert Pattinson, Zoë Kravitz, Paul Dano, Jeffrey Wright, John Turturro, Colin Farrell, Andy Serkis.	DC Films	Estados Unidos	6.9	https://www.youtube.com/embed/YNl8yV8oPZM?si=PDt0YLwL5mvKdpAf
3	Batman vs Superman: Dawn of Justice	https://www.lavanguardia.com/peliculas-series/images/movie/poster/2022/6/w1280/dQWpXwL2z4NdU86zn8Go3un8PmX.jpg	2016	Accion, Aventura, Ciencia ficción fantástica y Superheroes	151	Mientras el mundo debate qué tipo de héroe necesita, las hazañas de Superman tienen peligrosas consecuencias. En plena guerra entre el vigilante de Gotham y el defensor de Metrópolis, una nueva amenaza pone a la humanidad en grave peligro.	Zack Snyder	Ben Affleck, Henry Cavill, Amy Adams, Jesse Eisenberg, Diane Lane,  Laurence Fishburne, Jeremy Irons, Holly Hunter y Gal Gadot	Warner Bros. Pictures	Estados Unidos	5.5	https://www.youtube.com/embed/Vzi5Q5aIGJU?si=CJRr1Rnn0z8uEKZo
4	Batman (1989)	https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQSZugiOKWGmokjtfdCBbxYjkQI4byR13BPrw&s	1989	Acción, Aventura y Superhéroes.	126	El caballero oscuro conocido como Batman defiende a la corrupta e insegura ciudad de Gotham de su enemigo principal, un payaso homicida conocido como Joker..	Tim Burton	Jack Nicholson, Michael Keaton, Kim Basinger, Robert Wuhl, Pat Hingle, Billy Dee Williams, Michael Gough y Jack Palance.	PolyGram Filmed Entertainment	Estados Unidos	6.8	https://www.youtube.com/embed/ygK7sAavO0c?si=_O6Lec1Ol15H0v3-
5	Batman Returns 	https://m.media-amazon.com/images/M/MV5BOGZmYzVkMmItM2NiOS00MDI3LWI4ZWQtMTg0YWZkODRkMmViXkEyXkFqcGdeQXVyODY0NzcxNw@@._V1_.jpg	1992	Acción, Fantasía y Superhéroes.	126	Batman y la seductora Catwoman en la más oscura de sus aventuras, colaboran juntos para salvar la ciudad de Gotham, del Hombre Pingüino.	Tim Burton	Michael Keaton, Danny DeVito, Michelle Pfeiffer, Christopher Walken, Michael Gough, Pat Hingle, Michael Murphy y Vincent Schiavelli.	Warner Bros. Pictures	Estados Unidos	6.4	https://www.youtube.com/embed/YJ6tQBrsl-Y?si=5Jmns6wOtsiDTmxf
6	Batman y Robin 	https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRRafpOkLKjHKzCCa62FNF4lP1c7_qhSrykNg&s	1997	Superhéroes, Ciencia ficción, Acción, Aventura y Comedia.	125	Batman y su compañero Robin deben enfrentarse a un nuevo villano, el Sr. Frío, que intentará congelar a todos los habitantes de Gotham.	Joel Schumacher	George Clooney, Arnold Schwarzenegger, Uma Thurman, Alicia Silverstone, Robert Swenson, Michael Gough, Pat Hingle, John Glover y Elle Macpherson.	Warner Bros. Pictures	Estados Unidos	3.6	https://www.youtube.com/embed/JEo0ICIKk9c?si=5yC7XSRCW8j8nbcz
7	Batman Forever	https://m.media-amazon.com/images/M/MV5BNDdjYmFiYWEtYzBhZS00YTZkLWFlODgtY2I5MDE0NzZmMDljXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg	1995	Superhéroes, Ciencia ficción, Acción y Aventura.	121	La ciudad de Gotham está amenazada por dos hombres: Dos caras y un psicópata que ha inventado un aparato que permite absorber las ondas cerebrales de los seres humanos. Ambos se unirán para lograr sus propósitos.	Joel Schumacher	Val Kilmer, Tommy Lee Jones, Jim Carrey, Nicole Kidman, Michael Gough, Pat Hingle y Drew Barrymore.	Warner Bros. Pictures	Estados Unidos	4.6	https://www.youtube.com/embed/TkSgCsYAWY8?si=IbQJjrUDZ1g18FpE
8	The Lego Batman Movie	https://m.media-amazon.com/images/M/MV5BMTcyNTEyOTY0M15BMl5BanBnXkFtZTgwOTAyNzU3MDI@._V1_.jpg	2017	Animación, Superhéroes y Comedia.	104	El irreverente Batman, que también tiene algo de artista frustrado, intentará salvar la ciudad una vez más. Se están produciendo cambios en Gotham, y Batman tiene que salvar la ciudad del Joker, un peligroso villano. Sin embargo, Batman no podrá hacerlo solo y deberá aprender a trabajar con sus demás aliados.	Chris McKay	Will Arnett, Zach Galifianakis, Michael Cera, Rosario Dawson y Ralph Fiennes.	Warner Bros. Pictures	Estados Unidos	6.4	https://www.youtube.com/embed/JHxhTOxX_bs?si=Tmiq_g-fC2ACRk06
9	Batman: The Dark Knight	https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRGynrte4ZbbyvDGDQJltnfyoBqZE2fioii2g&s	2008	Acción, Crimen, Drama y Suspenso.	152	Con la ayuda del teniente Jim Gordon y del Fiscal del Distrito Harvey Dent, Batman mantiene a raya el crimen organizado en Gotham. Todo cambia cuando aparece el Joker, un nuevo criminal que desencadena el caos y tiene aterrados a los ciudadanos.	Christopher Nolan	Christian Bale, Michael Caine, Heath Ledger, Gary Oldman, Aaron Eckhart, Maggie Gyllenhaal y Morgan Freeman.	Warner Bros. Pictures	Estados Unidos	8.1	https://www.youtube.com/embed/EXeTwQWrcwY?si=VBgDVIcWeABLG-fv
1	Batman: Begins	https://es.web.img2.acsta.net/pictures/14/03/05/11/10/247578.jpg	2005	Accion, Crimen, Suspenso y Superheroes.	140	Bruce Wayne vive obsesionado con el recuerdo de la muerte de sus padres. Atormentado, se va de Gotham y encuentra a un extraño personaje que lo entrena en todas las disciplinas físicas y mentales que le servirán para combatir el Mal..	Christopher Nolan	Christian Bale, Michael Caine, Liam Neeson, Katie Holmes, Gary Oldman, Cillian Murphy, Tom Wilkinson,  Rutger Hauer, Ken Watanabe, Mark Boone Junior, Linus Roache, Morgan Freeman.	Warner Bros. Pictures	Estados Unidos	7.4	https://www.youtube.com/embed/BUt97Dv0y9E?si=WSAVtcL4G3hIrjrm" title="YouTube video player
17	El secreto de sus ojos	https://pics.filmaffinity.com/El_secreto_de_sus_ojos-650081510-large.jpg	2009	Suspenso y Drama.	127	Benjamín Espósito es un oficial de un Juzgado de Instrucción de Buenos Aires que acaba de jubilarse. Su sueño es escribir una novela y, para ello, intentará dar solución a un caso abierto desde hace varias décadas, del cual fue testigo y protagonista. Reviviendo el caso, vuelve también a su memoria el recuerdo de una mujer, a quien ha amado en silencio durante todos esos años.	Juan José Campanella	Ricardo Darín, Soledad Villamil, Pablo Rago, Javier Godino y Guillermo Francella.	Haddock Films	Argentina	8.1	https://www.youtube.com/embed/hKa8U-8vsfU?si=cKPq0YtnlilBq0Be
15	Top gun	https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSuvQjD4NLvQppSAdjm2nASuGwHLAfxKYj75Q&s	1986	Acción y Drama.	110	El joven piloto Maverick Mitchell acude a una prestigiosa escuela aérea, famosa por formar a los mejores pilotos de combate del país. Maverick se siente atraído por su hermosa instructora, mientras desarrolla una intensa rivalidad con otro piloto.	Tony Scott	Tom Cruise, Kelly McGillis, Val Kilmer, Anthony Edwards y Tom Skerritt.	Paramount Pictures	Estados Unidos	6.0	https://www.youtube.com/embed/xa_z57UatDY?si=d5qr5EsJbr6xbYDS
16	Top Gun: Maverick	https://es.web.img2.acsta.net/pictures/22/03/29/15/57/1533124.jpg	2022	Acción y Drama.	131	Maverick, quien lleva 30 años de servicio, es ahora instructor de pilotos militares. Una última misión, un sacrificio final, obliga a este maestro de los cielos a enfrentar las heridas abiertas del pasado y sus temores más profundos.	Joseph Kosinski	Tom Cruise, Val Kilmer, Miles Teller, Jennifer Connelly, Glen Powell, Lyliana Wray, Ed Harris, Monica Barbaro, Jon Hamm y Charles Parnell.	Paramount Pictures	Estados Unidos	7.0	https://www.youtube.com/embed/qSqVVswa420?si=PrTx5G9VFH4Kz3p3
112	El robo del siglo	https://es.web.img3.acsta.net/pictures/20/03/05/10/49/3147329.jpg	2020	Suspenso, crímenes y comedia.	114	Viernes, 13 de enero de 2006. Los policías aguardan la voz de su jefe. Miguel Sileo, el negociador, espera hablar con Vitette, uno de los líderes de la banda de ladrones que entró a la sucursal del Banco Río de Acassuso.	Ariel Winograd	Diego Peretti, Guillermo Francella, Pablo Rago, Luis Luque, Rafael Ferro y Mariano Argento.	AZ Films	Argentina	6.7	https://www.youtube.com/embed/8m6aAhgi7Xg?si=6jmdZU2KRz90neib
18	Star Wars: Episode I - The Phantom Menace	https://muvix.cl/CDN/media/entity/get/FilmPosterGraphic/A000000559?referenceScheme=Global&allowPlaceHolder=true	1999	Space opera, Blockbuster y Ciencia ficción.	136	Obi-Wan Kenobi es un joven aprendiz caballero Jedi bajo la tutela de Qui-Gon Jinn; Anakin Skywalker, quien después será padre de Luke Skywalker y se convertirá en Darth Vader, solamente es un niño de 9 años. Cuando la Federación de Comercio corta todas las rutas al planeta Naboo, Qui-Gon y Obi-Wan son asignados para solucionar el problema.	George Lucas	Liam Neeson, Ewan McGregor, Natalie Portman, Jake Lloyd, Pernilla August, Ray Park, Ahmed Best, Anthony Daniels, Kenny Baker,Hugh Quarshie, Ian McDiarmid, Silas Carson, Samuel L. Jackson y Frank Oz.	Lucasfilm	Estados Unidos	6.2	https://www.youtube.com/embed/n1CUHjrc9Sc?si=kxVTbY06BrU7Hkk1
10	Batman: The Dark Knight Rises	https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-hOXOOf4X2JM84kxuaUSLOXJwVi3q7L5oCQ&s	2012	Acción, Crimen, Drama y Suspenso.	165	Hace ya ocho años desde que Batman se convirtió en fugitivo al asumir la muerte de Harvey. La dura Ley Dent sigue aplacando la criminalidad de Gotham, aunque la llegada de una gata ladrona y un misterioso terrorista enmascarado lo cambiará todo.	Christopher Nolan	Christian Bale, Michael Caine, Gary Oldman, Anne Hathaway, Tom Hardy, Marion Cotillard, Joseph Gordon-Levitt, Morgan Freeman y Liam Neeson	Warner Bros. Pictures	Estados Unidos	7.5	https://www.youtube.com/embed/c_BZOsbX3MI?si=HerPhP6X54V8s74m
11	John Wick	https://m.media-amazon.com/images/M/MV5BMTU2NjA1ODgzMF5BMl5BanBnXkFtZTgwMTM2MTI4MjE@._V1_.jpg	2014	Acción, Aventura y Suspenso.	101	La ciudad de Nueva York se llena de balas cuando John Wick, un exasesino a sueldo, regresa de su retiro para enfrentar a los mafiosos rusos, liderados por Viggo Tarasov, que destruyeron todo aquello que él amaba y pusieron precio a su cabeza.	Chad Stahelskia​	Keanu Reeves, Mikael Nyqvist, Alfie Allen, Adrianne Palicki, Bridget Moynahan, Dean Winters, Ian McShane, John Leguizamo y Willem Dafoe.	MJW Films	Estados Unidos	6.4	https://www.youtube.com/embed/C0BMx-qxsP4?si=nnKKWyB5daSDC9b2
12	John Wick: Chapter 2	https://m.media-amazon.com/images/M/MV5BMjE2NDkxNTY2M15BMl5BanBnXkFtZTgwMDc2NzE0MTI@._V1_.jpg	2017	Acción, Aventura y Suspenso.	122	El legendario asesino John Wick se ve obligado a salir de su retiro por culpa de un exsocio que intenta controlar un siniestro grupo internacional de asesinos. Obligado a ayudarle por un juramento de sangre, John viaja a Roma para enfrentarse a algunos de los asesinos más letales del mundo.	Chad Stahelskia​	Keanu Reeves, Laurence Fishburne, Riccardo Scamarcio, Ruby Rose, Lance Reddick, Peter Stormare, Bridget Moynahan, Franco Nero, John Leguizamo e Ian McShane.	Summit Entertainment	Estados Unidos	6.4	https://www.youtube.com/embed/XGk2EfbD_Ps?si=5GxnyPGVaujE-Qyc
14	John Wick: Chapter 4	https://m.media-amazon.com/images/S/pv-target-images/6d3d1461d50778271845ce7ec81ba2c5d76a20f7f84e5061cd099aabaedc77f9.jpg	2023	Acción, Aventura y Suspenso.	169	El marqués Vincent de Gramont pretende matar a John Wick para afianzar su poder en la Orden Suprema. Sin embargo, John tratará de adelantarse a cada uno de sus movimientos hasta lograr enfrentarse cara a cara con su peor enemigo.	Chad Stahelskia​	Keanu Reeves, Laurence Fishburne, Ian McShane, Lance Reddick, Rina Sawayama, Donnie Yen, Shamier Anderson, Bill Skarsgård, Hiroyuki Sanada, Scott Adkins, Clancy Brown y Marko Zaror.	Thunder Road Pictures	Estados Unidos	6.7	https://www.youtube.com/embed/8ubRKDsM1FI?si=an_i3g45oK5VOCwq
19	Star Wars: Episode II - Attack Of The Clones	https://es.web.img2.acsta.net/medias/nmedia/18/90/04/31/20078125.jpg	2002	Space opera, Blockbuster y Ciencia ficción.	142	En el Senado Galáctico reina la inquietud. Varios miles de sistemas solares han declarado su intención de abandonar la República. Este movimiento separatista, liderado por el misterioso conde Dooku, ha provocado que al limitado número de caballeros Jedi les resulte difícil mantener la paz y el orden en la galaxia. La senadora Amidala, antigua Reina de Naboo, regresa al Senado Galáctico para dar su voto en la crítica cuestión de crear un ejército de la República que ayude a los desbordados Jedi.	George Lucas	Ewan McGregor, Hayden Christensen, Natalie Portman, Frank Oz, Ian McDiarmid, Pernilla August, Ahmed Best, Oliver Ford Davies, Temuera Morrison, Anthony Daniels, Silas Carson, Kenny Baker, Samuel L. Jackson y Christopher Lee.	Lucasfilm	Estados Unidos	6.3	https://www.youtube.com/embed/gYbW1F_c9eM?si=04iFksdxIewwZfy0
67	Matrix Revoluciones	https://es.web.img2.acsta.net/medias/nmedia/18/78/91/51/20076377.jpg	2003	Accion y Ciencia ficción.	129	Neo sigue adquiriendo nuevos poderes. Ahora, algo más cansado, ha llegado a la tierra de nadie, un tranquilo lugar entre Matrix y el mundo de las máquinas. Trinity vela el cuerpo en coma de Neo, mientras Morfeo se enfrenta a una revelación.	Hermanas Wachowski	Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss, Hugo Weaving, Monica Bellucci y Jada Pinkett Smith.	Warner Bros. Pictures	Estados Unidos y Australia	6.0	https://www.youtube.com/embed/hMbexEPAOQI?si=0ix1_e441uavRU_y
26	Star Wars: Episode IX - The Last Jedi	https://www.animeworld.com.ar/mods/html/fil/Model/Product/3299/estrenos_marzo_2020_-_semana_2_-_star_wars_episodio_9_copy.jpg.webp	2019	Accion, Aventura, Space opera, Blockbuster y Ciencia ficción.	142	La Resistencia sobreviviente se enfrenta a la Primera Orden, y Rey, Finn, Poe y el resto de los héroes encararán nuevos retos y una batalla final con la sabiduría de las generaciones anteriores.	J.J. Abrams	Carrie Fisher, Mark Hamill, Adam Driver, Daisy Ridley, John Boyega, Oscar Isaac, Anthony Daniels, Naomi Ackie, Domhnall Gleeson, Richard E. Grant, Keri Russell, Joonas Suotamo, Kelly Marie Tran, Ian McDiarmid y Billy Dee Williams.	Lucasfilm	Estados Unidos	5.6	https://www.youtube.com/embed/8Qn_spdM5Zg?si=-iBsreNi5k_wX6E8
68	Matrix: Resurrecciones	https://play-lh.googleusercontent.com/H6Ioa-dJbdily7_7kbL6ZLPaZXpm8T5fOfTAwZYa7UXjtR30ekNWD2ZHl2HwI_WcT0E-D7ZZ4uxcJfuvwTDw	2021	Accion y Ciencia ficción.	147	Thomas Anderson lleva una vida cómoda como una eminencia dentro del mundo de los videojuegos, pero tiene problemas para discernir entre lo que es realidad y lo que no lo es. Thomas deberá decidir si sigue al conejo blanco una vez más.	Lana Wachowski	Keanu Reeves, Carrie-Anne Moss, Jada Pinkett Smith, Lambert Wilson, Priyanka Chopra, Daniel Bernhardt, Neil Patrick Harris, Jonathan Groff, Christina Ricci, Jessica Henwick, Eréndira Ibarra y Yahya Abdul-Mateen II.	Warner Bros. Pictures	Estados Unidos	4.9	https://www.youtube.com/embed/Rw5JzpvJTfM?si=SRL-4MiJZPwjARZs
20	Star Wars: Episode III - Revange Of The Sinth	https://m.media-amazon.com/images/S/pv-target-images/3a991f1ad651779c8701339593c0a7c6afa18ba8844da38a1740e9fea2ebe873.jpg	2005	Accion, Aventura, Space opera, Blockbuster y Ciencia ficción.	139	La República se desmorona bajo los ataques del despiadado Lord Sith, el conde Dooku. Hay héroes en ambos bandos, pero el mal está por doquier. En una contundente jugada, el diabólico líder droide, el general Grievous, ha irrumpido en la capital de la República y ha secuestrado al Canciller Palpatine, líder del senado Galáctico. Mientras el ejército droide separatista trata de huir con su valioso rehén, Obi Wan y Anakin inician una misión desesperada para liberar al Canciller cautivo.	George Lucas	Ewan McGregor, Hayden Christensen, Natalie Portman, Ian McDiarmid, Samuel L. Jackson, Christopher Lee, Anthony Daniels, James Earl Jones, Kenny Baker y Frank Oz.	Lucasfilm	Estados Unidos	7.1	https://www.youtube.com/embed/5UnjrG_N8hU?si=u-knAIQ_1CpihZXt
23	Star Wars: Episode VI - Return Of The Jedi	https://www.hobbyconsolas.com/sites/navi.axelspringer.es/public/media/image/2016/11/guerra-galaxias-episodio-vi-retorno-jedi_0.jpg	1983	Accion, Aventura, Space opera, Blockbuster y Ciencia ficción.	128	Seis meses después de que Han Solo fuera capturado y congelado en carbonita en la Ciudad de las Nubes, el Imperio Galáctico está construyendo una nueva Estrella de la Muerte. Mientras tanto, el joven Luke lucha para alcanzar la maestría jedi.	George Lucas	Mark Hamill, James Earl Jones, David Prowse, Sebastian Shaw, Harrison Ford, Carrie Fisher, Billy Dee Williams, Anthony Daniels, Kenny Baker, Peter Mayhew, Ian McDiarmid, Frank Oz y Alec Guinness.	Lucasfilm	Estados Unidos	7.9	https://www.youtube.com/embed/p4vIFhk621Q?si=KOWiTVZXI1kp3JbM
21	Star Wars: Episode IV - A New Hope	https://assets.scriptslug.com/live/img/posters/star-wars-episode-iv-a-new-hope-1977.jpg?utime=20240519142212	1977	Accion, Aventura, Space opera, Blockbuster y Ciencia ficción.	121	La nave en la que viaja la princesa Leia es capturada por las tropas imperiales al mando del temible Darth Vader. Antes de ser atrapada, Leia consigue introducir un mensaje en su robot R2-D2, quien acompañado de su inseparable C-3PO logran escapar. Tras aterrizar en el planeta Tattooine son capturados y vendidos al joven Luke Skywalker, quien descubrirá el mensaje oculto que va destinado a Obi Wan Kenobi, maestro Jedi a quien Luke debe encontrar para salvar a la princesa.	George Lucas	Mark Hamill, Harrison Ford, Carrie Fisher, Peter Cushing, Alec Guinness, Anthony Daniels, Kenny Baker, Peter Mayhew, David Prowse, Jack Purvis, Eddie Byrne y James Earl Jones.	Lucasfilm	Estados Unidos	7.9	https://www.youtube.com/embed/vZ734NWnAHA?si=Au30x7vzgqjp66tv
24	Star Wars: Episode VII - The Force Awakens	https://image.tmdb.org/t/p/original/wG3nQWTclxQqmr3i3dReSbB6bOF.jpg	2015	Accion, Aventura, Space opera, Blockbuster y Ciencia ficción.	136	Treinta años después de la victoria de la Alianza Rebelde sobre la segunda Estrella de la Muerte, la galaxia tiene que enfrentarse a una nueva amenaza: el malvado Kylo Ren y la Primera Orden. Cuando el desertor Finn llega a un planeta desierto conoce a Rey, cuyo androide contiene un mapa secreto. Juntos, la joven pareja unirá fuerzas con Han Solo para asegurarse de que la resistencia encuentra a Luke Skywalker, el último de los caballeros Jedi.	J. J. Abrams	Mark Hamill, James Earl Jones, David Prowse, Sebastian Shaw, Harrison Ford, Carrie Fisher, Billy Dee Williams, Anthony Daniels, Kenny Baker, Peter Mayhew, Ian McDiarmid, Frank Oz y Alec Guinness.	Lucasfilm	Estados Unidos	6.7	https://www.youtube.com/embed/sGbxmsDFVnE?si=5EJvlEYT64meaeF9
69	Máxima velocidad	https://mx.web.img3.acsta.net/pictures/18/10/01/06/08/2542886.jpg	1994	Accion.	116	Jack Traven, interpretado por Keanu Reeves, es un policía de Los Ángeles que se enfrenta a uno de los mayores retos de su carrera: tratar de dar caza a un peligroso terrorista llamado Howard Payne (Hopper), el cual ha puesto una bomba en un autobús de la ciudad que explotará si disminuye su velocidad por debajo de las 50 millas por hora.	Jan de Bont	Keanu Reeves, Sandra Bullock, Dennis Hopper, Joe Morton y Jeff Daniels.	20th Century Fox	Estados Unidos	5.9	https://www.youtube.com/embed/icKnWa_Thlk?si=a7AIv5kEVYlCHR6k
33	Terminator 3: Rise Of The Machines 	https://m.media-amazon.com/images/M/MV5BMTk5NzM1ODgyN15BMl5BanBnXkFtZTcwMzA5MjAzMw@@._V1_.jpg	2003	Ciencia ficcion y Acción.	109	Un robot de un futuro postapocalíptico viaja en el tiempo con la misión de proteger a John Connor y a su futura esposa de un modelo cibernético más sofisticado que ha sido enviado para matarlo y asegurar el triunfo de las máquinas sobre los humanos.	Jonathan Mostow.	Arnold Schwarzenegger, Nick Stahl, Claire Danes, Kristanna Loken y David Andrews.	C2 Pictures	Estados Unidos	5.2	https://www.youtube.com/embed/5UgPJhyJmlM?si=62XZ7DEDcg0OJDeO
34	Terminator Salvation 	https://m.media-amazon.com/images/M/MV5BODBlOTJhZjItMGRmYS00YzM1LWFmZTktOTJmNDMyZTBjMjBkXkEyXkFqcGdeQXVyMjMwNDgzNjc@._V1_FMjpg_UX1000_.jpg	2009	Ciencia ficcion y Acción.	118	Mientras las máquinas se preparan para un ataque final, John Connor y un extraño entran en el corazón de Skynet y descubren que va a haber una terrible masacre.	Joseph McGinty Nichol.	Christian Bale, Sam Worthington, Anton Yelchin, Bryce Dallas Howard, Moon Bloodgood, Common, Helena Bonham Carter y Michael Ironside.	The Halcyon Company	Estados Unidos	5.9	https://www.youtube.com/embed/-Czz-TcWCkA?si=uSKy6OcMzCYdW9eG
35	Terminator Genesis 	https://im.ziffdavisinternational.com/ign_es/screenshot/default/terminatorintlposter1_7s3r.jpg	2015	Ciencia ficcion y Acción.	126	En Los Ángeles del año 2032, John Connor, líder de la resistencia humana contra las máquinas que se han apoderado de la Tierra, prepara la ofensiva definitiva contra Skynet. Junto a él lucha su mano derecha, el sargento Kyle Reese. Connor envía a Reese a 1984 para salvar a su madre, Sarah, de un Terminator.	Alan Taylor.	Arnold Schwarzenegger, Jai Courtney, Emilia Clarke y Jason Clarke.	Skydance Productions.	Estados Unidos	5.2	https://www.youtube.com/embed/0vrj9V-vYZc?si=G2V9VnZXHWjQkhlH
31	Terminator 1	https://es.web.img3.acsta.net/pictures/16/02/12/15/14/218373.jpg	1984	Ciencia ficcion y Acción.	108	En el año 2029 las máquinas dominan el mundo. Los rebeldes que luchan contra ellas tienen como líder a John Connor, un hombre que nació en los años ochenta. Para eliminarlo y así acabar con la rebelión, las máquinas envían al pasado el robot Terminator con la misión de matar a Sarah Connor, la madre de John, e impedir así su nacimiento. Sin embargo, un hombre del futuro intentará protegerla.	James Cameron	Arnold Schwarzenegger, Linda Hamilton y Michael Biehn.	Hemdale Film Corporation	Estados Unidos	7.1	https://www.youtube.com/embed/k64P4l2Wmeg?si=tA7H3QRmgh4iWv7V
29	Kung Fu Panda 3	https://m.media-amazon.com/images/M/MV5BMTUyNzgxNjg2M15BMl5BanBnXkFtZTgwMTY1NDI1NjE@._V1_FMjpg_UX1000_.jpg	2016	Animación, Aventura, Comedia y Acción.	95	El malvado Kai, confinado en el reino de los espíritus desde hace 500 años, consigue arrebatarle el chi al maestro Oogway, lo que le permite regresar al mundo de los mortales. Po deberá hacer frente a dos desafíos épicos: uno, de origen sobrenatural; el otro, muy cerca de su hogar, con la aparición del que dice ser su padre biológico.	Jennifer Yuh Nelson	Jack Black, Bryan Cranston, James Hong, Dustin Hoffman, Angelina Jolie, J. K. Simmons, Seth Rogen, Lucy Liu, David Cross, Kate Hudson, Randall Duk Kim, Wayne Knight y Jackie Chan.	DreamWorks Animation	Estados Unidos	6.0	https://www.youtube.com/embed/xADC5FrVeTs?si=cD2KDUb1vVhAF3Cs
27	Kung Fu Panda	https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQCvhtLQ80OqelAWJn4PsbFao1MQyh2B3EOeg&s	2008	Animación, Aventura, Comedia y Acción.	92	El panda Po trabaja en la tienda de fideos de su familia y que sueña en convertirse en un maestro del kung-fu, se hace una realidad cuando es inesperadamente elegido para cumplir una antigua profecía y debe estudiar artes marciales con sus ídolos, los Cinco Furiosos. Po necesitará toda la sabiduría, fortaleza y habilidades para poder proteger a su gente de Tai Lung, un leopardo de nieve.	Mark Osborne	Jack Black, Jackie Chan, Dustin Hoffman, Angelina Jolie, Seth Rogen, Ian McShane, Lucy Liu y David Cross.	DreamWorks Animation	Estados Unidos	6.5	https://www.youtube.com/embed/NRc-ze7Wrxw?si=VmJUchM0VGwe6cP6
32	Terminator 2: Judgment Day 	https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSJliUrAgkzbhnBCs5flMdshgTd80WpLmjpGw&s	1991	Ciencia ficcion y Acción.	137	Algunos años antes, un viajero del tiempo le reveló a la madre de John que su hijo sería el salvador de la humanidad. Cuando un nuevo androide mejorado llega del futuro para asesinar a John, un viejo modelo será enviado para protegerle.	James Cameron	Arnold Schwarzenegger, Linda Hamilton, Edward Furlong y Robert Patrick.	Carolco Pictures	Estados Unidos	7.5	https://www.youtube.com/embed/CRRlbK5w8AE?si=1ieSGC4Xnbh-hCzP
30	Kung Fu Panda 4	https://es.web.img3.acsta.net/pictures/23/12/20/17/49/3528056.jpg	2024	Animación, Aventura, Comedia y Acción.	94	Po está entrenando a un nuevo guerrero que ocupe su lugar para que él pueda convertirse en líder espiritual del Valle de la Paz. Sin embargo, la irrupción de una malvada hechicera que puede cambiar de apariencia trastoca sus planes.	Mike Mitchell	Jack Black, Viola Davis, Dustin Hoffman, James Hong, Bryan Cranston, Ian McShane, Ke Huy Quan, Angelina Jolie y Seth Rogen.	DreamWorks Animation	Estados Unidos	5.7	https://www.youtube.com/embed/tYMDHo9xy1I?si=HNcsAJDNjSsDso5L
70	La lista de Schindler	https://pics.filmaffinity.com/La_lista_de_Schindler-473662617-large.jpg	1993	Cine bélico, cine biográfico y drama	195	El empresario alemán Oskar Schindler, miembro del Partido Nazi, pone en marcha un elaborado, costoso y arriesgado plan para salvar a más de mil judíos del Holocausto.	Steven Spielberg	Liam Neeson, Ralph Fiennes, Ben Kingsley, Caroline Goodall, Embeth Davidtz y Jonathan Sagall.	Universal Pictures	Estados Unidos	8.7	https://www.youtube.com/embed/gG22XNhtnoY?si=2XQkjrIbGGFJeunN
42	Volver al futuro III	https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTtuVvd8yahD-VoRYT__hJhCZd9LhPto0rHmA&s	1990	Ciencia Ficcion,Comedia, Western y Aventura	119	Marty McFly sigue en 1955 y Doc ha retrocedido al año 1885, la época del salvaje oeste. Marty recibe una carta de Doc en la que le informa de que la máquina del tiempo está averiada y no puede volver al presente, pero que no le importa seguir en el pasado. Sin embargo, Marty descubre una tumba en la que lee que Doc murió en 1885 y decide ir a rescatar a su amigo.	Robert Zemeckis.	Michael J. Fox, Christopher Lloyd, Mary Steenburgen, Thomas F. Wilson y Lea Thompson.	Universal Pictures	Estados Unidos	6.6	https://www.youtube.com/embed/WmBX7CA-AAc?si=JCRmc7nH4LFRtUae
45	Alien 3	https://es.web.img3.acsta.net/c_310_420/medias/nmedia/18/78/65/71/20076549.jpg	1992	Ciencia Ficcion, Accion y Terror	114	Ripley libera a un grupo de convictos desarmados en un desesperado intento de matar al extraterrestre que los persigue.	David Fincher.	Sigourney Weaver, Lance Henriksen, Charles S. Dutton, Charles Dance, Paul McGann, Pete Postlethwaite.	20th Century Fox.	Estados Unidos	5.9	https://www.youtube.com/embed/O57vJ59Eq5Q?si=LfGIYf7ul3xkBZ9T
36	Terminator: Dark Fate 	https://es.web.img3.acsta.net/pictures/19/09/03/16/58/5053583.jpg	2019	Ciencia ficcion y Acción.	128	En Ciudad de México, un nuevo Terminator modificado, también conocido como Rev-9, llega del futuro para matar a una joven trabajadora de una fábrica llamada Dani Ramos. La cyborg híbrida Grace también es enviada al pasado para proteger a Ramos del aparentemente indestructible Rev-9. Las dos mujeres pronto recibirán ayuda de un par de aliados inesperados: la experimentada luchadora de la resistencia Sarah Connor y el T-800.	Tim Miller.	Linda Hamilton, Arnold Schwarzenegger, Mackenzie Davis, Natalia Reyes y Gabriel Luna.	Paramount Pictures.	Estados Unidos	5.2	https://www.youtube.com/embed/2LKDwZlggNI?si=Y3PEwbaYy_Y53-Hj
38	El Señor de los Anillos: Las Dos Torres	https://es.web.img3.acsta.net/medias/nmedia/18/89/85/69/20070008.jpg	2002	Aventura y Fantasía épica.	172	Los hobbits Frodo y Sam descubren que Gollum les está siguiendo. La criatura les promete guiarlos hasta las puertas de Mordor si después lo dejan libre. Aragorn, el elfo Legolas y Gimli el enano llegan al reino de Rohan y descubren que el rey Theoden está bajo el conjuro de Sarumán. El traidor quiere el control del reino para continuar con sus planes en Mordor, a la espera de la guerra en la Tierra Media.	Peter Jackson.	Elijah Wood, Ian McKellen, Liv Tyler, Viggo Mortensen, Sean Astin, Billy Boyd, Dominic Monaghan, John Rhys-Davies, Christopher Lee, Orlando Bloom, Karl Urban, Bernard Hill, Miranda Otto y Andy Serkis.	New Line Cinema.	Estados Unidos y Nueva Zelanda	8.0	https://www.youtube.com/embed/Qmwq4viqxXQ?si=A7tXU9e9oZ_o2tKL
39	El Señor de los Anillos: El Retorno Del Rey	https://es.web.img2.acsta.net/medias/nmedia/18/89/68/19/20061877.jpg	2003	Aventura y Fantasía épica.	201	La batalla por la Tierra Media ha empezado. Las fuerzas de Saruman han sido destruidas y por primera vez parece que hay una pequeña esperanza. Sin embargo, el poder de Sauron crece y su interés se centra en Gondor, el último reducto de los hombres, cuyo heredero es Aragorn. Mientras, Frodo y Sam, guiados por Gollum, siguen su peligrosa misión a través de Mordor para destruir el anillo.	Peter Jackson.	Elijah Wood, Ian McKellen, Liv Tyler, Viggo Mortensen, Sean Astin, Billy Boyd, Dominic Monaghan, Orlando Bloom, John Rhys-Davies, John Noble, David Wenham, Bernard Hill , Miranda Otto, Karl Urban y Andy Serkis.	New Line Cinema.	Estados Unidos y Nueva Zelanda	8.2	https://www.youtube.com/embed/mZYms2vsm2Y?si=0-8k71dy9K_uggXs
40	Volver al Futuro	https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSARwCFB6M36a-YEdVSHKjbJjAiic23UyYlvA&s	1985	Ciencia Ficcion,Comedia y Aventura.	117	El adolescente Marty McFly es amigo de Doc, un científico que ha construido una máquina del tiempo. Cuando los dos prueban el artefacto, un error fortuito hace que Marty llegue a 1955, año en el que sus padres iban al instituto y todavía no se habían conocido. Después de impedir su primer encuentro, Marty deberá conseguir que se conozcan y se enamoren, de lo contrario su existencia no sería posible.	Robert Zemeckis.	Michael J. Fox, Christopher Lloyd, Lea Thompson, Crispin Glover, Thomas F. Wilson y Marc McClure.	Universal Pictures.	Estados Unidos	7.5	https://www.youtube.com/embed/8x0s7U0DBWI?si=1NgQOvsXzPSGz1XD
41	Volver al futuro II	https://es.web.img3.acsta.net/pictures/14/04/03/13/45/034916.jpg	1989	Ciencia Ficcion,Comedia y Aventura.	109	Doc vuelve a aparecer con una máquina del tiempo mucho más modernizada y le pide a Marty y a su novia que le acompañen al futuro. En el Hill Valley de 2015 deberán solucionar un problema con la ley que tendrá uno de los futuros hijos de Marty y Jenny. En el futuro, Biff Tannen roba la máquina del tiempo y vuelve al pasado para darle a su hijo un libro con estadísticas deportivas para poder ganar una enorme fortuna en las apuestas. Marty y Doc tendrán que parar la posible catástrofe del destino.	Robert Zemeckis.	Michael J. Fox, Christopher Lloyd, Lea Thompson, Crispin Glover, Thomas F. Wilson y Marc McClure.	Amblin Entertainment.	Estados Unidos	7.2	https://www.youtube.com/embed/ixLXR27eGCw?si=U838Acy2OfVovfpt
44	Alien 2: El regreso	https://4.bp.blogspot.com/-kCfTovg5GgU/TgpZT89_XRI/AAAAAAAAA8w/ToJL1pxIBgo/s1600/Alien+2.jpg	1986	Ciencia Ficcion, Accion y Terror	137	La sobreviviente de un ataque extraterrestre regresa al planeta LV-426 acompañada por unos marines. Juntos, deberán destruir a un monstruo.	James Cameron.	Sigourney Weaver, Michael Biehn, Lance Henriksen, Carrie Henn, Bill Paxton, Paul Reiser.	20th Century Fox.	Estados Unidos	7.4	https://www.youtube.com/embed/LRQJEcmo4-8?si=DqoHaxfVnyLh98rd
47	Alien: Prometheus	https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRshf-IJduGlIbItIQmy0Gfs0PVK9wY20W0xA&s	2012	Ciencia Ficcion y Terror	124	La acción comienza en un planeta sin vida humana aparente. Al borde de una cascada, un extraterrestre humanoide espera mientras una enorme nave espacial, que permanecía inmóvil, empieza a alejarse. El humanoide bebe un líquido negro burbujeante y empieza a desintegrarse. Cuando sus restos corporales caen por la cascada, el ADN del extraterrestre sufre una reacción biogenética.	Ridley Scott.	Noomi Rapace, Michael Fassbender, Charlize Theron, Idris Elba, Guy Pearce, Logan Marshall-Green	20th Century Fox.	Estados Unidos	5.8	https://www.youtube.com/embed/aUwNASUI4y8?si=j_qnWI-manoj9LrF
48	Alien Covenant 	https://play-lh.googleusercontent.com/Cy39VIudZjv00OUTR1Nt6h_68aLU6g8xAdWEDDEuMJt6QmP9ihpFVqSsXNZxEDamwnmx	2017	Ciencia Ficcion y Terror	122	Durante un viaje interplanetario, la tripulación de la nave Covenant descubre un mundo nuevo y piensan que se trata de un lugar paradisíaco. Cuando llegan, se dan cuenta de que es un territorio aterrador, repleto de criaturas brutales. Mientras lo exploran se percatan de que no son los primeros en aterrizar en ese planeta.	Ridley Scott.	Michael Fassbender, Katherine Waterston, Billy Crudup, Danny McBride, Guy Pearce	20th Century Fox.	Estados Unidos	5.6	https://www.youtube.com/embed/_O6YW4Rxubk?si=nY0CIv7wLxEG7SLy
46	Alien: Resurrección	https://musicart.xboxlive.com/7/8fb00800-0000-0000-0000-000000000002/504/image.jpg?w=1920&h=1080	1992	Ciencia Ficcion y Terror	109	Doscientos años después del sacrificio de Ripley para destruir al alien que quedaba en la galaxia, la teniente vuelve a la vida gracias a la clonación.	Jean-Pierre Jeunet.	Sigourney Weaver, Winona Ryder, Dominique Pinon, Ron Perlman, Gary Dourdan, Michael Wincott, Kim Flowers, Dan Hedaya, J.E. Freeman, Brad Dourif, Raymond Cruz, Leland Orser, Carolyn Campbell, Marlene Bush, David St. James	20th Century Fox.	Estados Unidos	5.6	https://www.youtube.com/embed/zu4WMF1yugo?si=sbB5v5HsgcDRBt_x
50	Los juegos del hambre: En llamas	https://es.web.img2.acsta.net/pictures/210/455/21045552_20131001101323189.jpg	2013	Ciencia ficción, Acción, Drama y Distopía	146	Katniss Everdeen volvió a casa a salvo después de ganar la 74 edición de los Juegos del Hambre con su compañero Peeta. Sin embargo, ahora el Capitolio les obliga a abandonar de nuevo a su familia y amigos para participar en el Tour de la Victoria por todos los distritos. Mientras, el presidente Snow está preparando una nueva edición de los Juegos, que transformarán Panem para siempre.	Francis Lawrence	Jennifer Lawrence, Josh Hutcherson, Liam Hemsworth, Woody Harrelson, Elizabeth Banks, Lenny Kravitz, Philip Seymour Hoffman, Jeffrey Wright, Stanley Tucci, Sam Claflin, Jena Malone, Donald Sutherland	Warner Bros Pictures.	Estados Unidos	6.4	https://www.youtube.com/embed/wTwabD43r2w?si=TtJou21Y5wnkoNIA
43	Alien 1: El octavo pasajero	https://images.justwatch.com/poster/9890794/s718/alien-el-octavo-pasajero.jpg	1979	Ciencia Ficcion y Terror	116	La tripulación del remolcador espacial Nostromo atiende una señal de socorro y, sin saberlo, sube a bordo una letal forma de vida extraterrestre.	Robert Zemeckis.	Tom Skerritt, Sigourney Weaver, Veronica Cartwright, Harry Dean Stanton, John Hurt, Ian Holm, Yaphet Kotto, Bolaji Badejo.	20th Century Fox.	Estados Unidos	8.1	https://www.youtube.com/embed/6q0I-OqZP14?si=AcAI_p1enw_Aonn1
51	Los juegos del hambre: Sinsajo- Parte 1	https://es.web.img3.acsta.net/pictures/14/09/12/10/51/011753.jpg	2014	Ciencia ficción, Acción, Drama y Distopía	146	Katniss Everdeen se encuentra en el Distrito 13 después de destrozar los juegos para siempre. Bajo el liderazgo de la comandante Coin y el consejo de sus amigos más leales, Katniss extiende sus alas mientras lucha por salvar a Peeta Mellark y a una nación alentada por su valentía.	Francis Lawrence	Sam Claflin, Jennifer Lawrence, Josh Hutcherson, Liam Hemsworth, Woody Harrelson, Elizabeth Banks, Julianne Moore, Jena Malone, Philip Seymour Hoffman, Stanley Tucci, Donald Sutherland	Warner Bros Pictures.	Estados Unidos	5.6	https://www.youtube.com/embed/3AuMlTD46tg?si=0wCday1XaHl2on-q
52	Los juegos del hambre: Sinsajo- Parte 2	https://es.web.img2.acsta.net/pictures/15/10/05/09/45/058912.jpg	2015	Ciencia ficción, Acción, Drama y Distopía	137	Finalmente el Distrito 13 consigue rescatar de las garras del Capitolio a Peeta Mellark. Las torturas psicológicas han hecho mella en el joven y está convencido de que Katniss es una peligrosa muto con la que hay que acabar. Junto con un grupo de amigos, Peeta y Katniss emprenden una arriesgada misión para liberar Panem. La joven heroína se dará cuenta de que no sólo está en juego su supervivencia, sino que también el futuro de todos.	Francis Lawrence	Jennifer Lawrence, Josh Hutcherson, Liam Hemsworth, Woody Harrelson, Elizabeth Banks, Julianne Moore, Philip Seymour Hoffman, Jeffrey Wright, Stanley Tucci, Donald Sutherland, Sam Claflin	Warner Bros Pictures.	Estados Unidos	5.6	https://www.youtube.com/embed/3-ar77u-Mww?si=SWssI4cvocK9E2VU
53	Los juegos del hambre: Balada de pájaros cantores y serpientes	https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcReneMC1Wf0RWECUX6uFCeywk0ebqFTI0RTiw&s	2023	Acción, Drama y Aventura	158	Muchos años antes de convertirse en Presidente de Panem, el joven Coriolanus Snow es elegido mentor del Distrito 12 en los nuevos Juegos del Hambre. Aquí utiliza su encanto, astucia e inventiva para ayudar a su candidata a ganar.	Francis Lawrence	Tom Blyth, Rachel Zegler, Josh Andrés Rivera, Hunter Schafer, Jason Schwartzman, Burn Gorman, Peter Dinklage, Viola Davis	Warner Bros Pictures.	Estados Unidos	5.8	https://www.youtube.com/embed/IWjAy4lIyoY?si=YxvrTS0rcsy5zwUo
54	El niño con el pijama a rayas	https://es.web.img3.acsta.net/medias/nmedia/18/67/06/38/20350558.jpg	2008	Drama y Cine belico	94	Durante la Segunda Guerra Mundial, el pequeño hijo de un comandante de un campo de concentración desarrolla una amistad prohibida con un niño judío de 8 años.	Mark Herman	Vera Farmiga, David Thewlis, Rupert Friend, Asa Butterfield y Jack Scanlon	Miramax Films	Reino unido	6.9	https://www.youtube.com/embed/dRUe8JR8iWY?si=gf1bG21fvKVIA3WE
55	E.T., el extraterrestre	https://pics.filmaffinity.com/E_T_el_extraterrestre-391240254-large.jpg	1982	Ciencia ficcion.	114	Un pequeño extraterrestre de otro planeta queda abandonado en la Tierra cuando su nave se olvida de él. Está completamente solo y asustado hasta que Elliott, un niño de nueve años, lo encuentra y decide esconderlo en su casa para protegerlo. El chico y sus hermanos intentarán encontrar la forma de devolver al extraterrestre a su planeta antes de que lo encuentren los científicos y la policía.	Steven Spielberg	Henry Thomas, Robert MacNaughton, Drew Barrymore, Dee Wallace, Peter Coyote, K. C. Martel, Sean Frye, C. Thomas Howell, Erika Eleniak, Pat Welsh	Universal Pictures	Estados Unidos	7.5	https://www.youtube.com/embed/jzC0c-GWeDQ?si=_NyRxIeNba2GMpfs
13	John Wick: Chapter 3 Parabellum	https://musicart.xboxlive.com/7/261e5100-0000-0000-0000-000000000002/504/image.jpg?w=1920&h=1080	2019	Acción, Aventura y Suspenso.	131	John Wick regresa de nuevo pero con una recompensa sobre su cabeza que persigue unos mercenarios. Tras asesinar a uno de los miembros de su gremio, Wick es expulsado y se convierte en el foco de atención de todos los sicarios de la organización.	Chad Stahelskia​	Keanu Reeves, Halle Berry, Laurence Fishburne, Mark Dacascos, Asia Kate Dillon, Lance Reddick, Anjelica Huston e Ian McShane.	Summit Entertainment	Estados Unidos	6.4	https://www.youtube.com/embed/pU8-7BX9uxs?si=aAjISwFWTBlUqBiM
25	Star Wars: Episode VIII - The Last Jedi	https://hips.hearstapps.com/hmg-prod/images/los-ultimos-jedi-1575448992.jpg?crop=1xw:1xh;center,top&resize=980:*	2017	Accion, Aventura, Space opera, Blockbuster y Ciencia ficción.	152	La Primera Orden ha acorralado a los últimos miembros de la resistencia. Su última esperanza es que Finn se introduzca en la nave de Snoke y desactive el radar que les permite localizarlos. Mientras él trata, en compañía de una soldado de la Resistencia, de cumplir esta misión imposible, Rey se encuentra lejos, intentando convencer a Luke Skywalker de que la entrene y la convierta en la última jedi.	Rian Johnson	Mark Hamill, Carrie Fisher, Adam Driver, Daisy Ridley, John Boyega, Oscar Isaac, Andy Serkis, Domhnall Gleeson, Anthony Daniels, Gwendoline Christie, Kelly Marie Tran, Laura Dern, Frank Oz, Benicio Del Toro y Jimmy Vee.	Lucasfilm	Estados Unidos	6.1	https://www.youtube.com/embed/Q0CbN8sfihY?si=fmpRNVzPrx-gaYUp
37	El Señor de los Anillos: La Comunidad del Anillo	https://es.web.img3.acsta.net/medias/nmedia/18/89/67/45/20061512.jpg	2001	Aventura y Fantasía épica.	178	En la Tierra Media, el Señor Oscuro Sauron forjó los Grandes Anillos del Poder y creó uno con el poder de esclavizar a toda la Tierra Media. Frodo Bolsón es un hobbit al que su tío Bilbo hace portador del poderoso Anillo Único con la misión de destruirlo. Acompañado de sus amigos, Frodo emprende un viaje hacia Mordor, el único lugar donde el anillo puede ser destruido. Sin embargo, Sauron ordena la persecución del grupo para recuperar el anillo y acabar con la Tierra Media.	Peter Jackson.	Elijah Wood, Ian McKellen, Liv Tyler, Viggo Mortensen, Sean Astin, Cate Blanchett, John Rhys-Davies, Billy Boyd, Dominic Monaghan, Orlando Bloom, Christopher Lee, Hugo Weaving, Sean Bean, Ian Holm, Andy Serkis, Marton Csokas y Craig Parker.	New Line Cinema.	Estados Unidos y Nueva Zelanda	8.0	https://www.youtube.com/embed/3GJp6p_mgPo?si=HMZOuDLfH3GM7URO
57	Forest Gump	https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTcp2IxZC1XOBPtu1KOifG2FKyu83jD1JsKBQ&s	1994	Comedia y Drama.	142	Sentado en un banco en Savannah, Georgia, Forrest Gump espera al autobús. Mientras éste tarda en llegar, el joven cuenta su vida a las personas que se sientan a esperar con él. Aunque sufre un pequeño retraso mental, esto no le impide hacer cosas maravillosas. Sin entender del todo lo que sucede a su alrededor, Forrest toma partido en los eventos más importantes de la historia de los Estados Unidos.	Robert Zemeckis	Tom Hanks, Robin Wright, Gary Sinise, Mykelti Williamson, Sally Field y Michael Conner Humphreys.	Paramount Pictures	Estados Unidos	8.2	https://www.youtube.com/embed/GIs2gpWpBiQ?si=xp6dWarpr1EJ1HF6
58	Rescatando al soldado Ryan	https://pics.filmaffinity.com/Salvar_al_soldado_Ryan-442865234-large.jpg	1998	Bélico, Drama, Aventura, Cine belico y Épica.	169	Después de desembarcar en Normandía, en plena Segunda Guerra Mundial, unos soldados norteamericanos deben arriesgar sus vidas para salvar al soldado James Ryan, cuyos tres hermanos han muerto en la guerra.	Steven Spielberg	Tom Hanks, Tom Sizemore, Edward Burns, Matt Damon, Jeremy Davies, Adam Goldberg, Barry Pepper, Giovanni Ribisi y Vin Diesel.	Paramount Pictures y DreamWorks Pictures	Estados Unidos	7.8	https://www.youtube.com/embed/TAyhMtyup3o?si=W__2tqCevrQXvFp6
59	American Psycho	https://es.web.img3.acsta.net/medias/nmedia/18/67/08/57/18971592.gif	2000	Terror, Thriller y Humor negro.	101	En la década de 1980, Patrick Bateman es un hombre exitoso y obsesionado por la competencia y por la perfección material, quien utiliza los más caros cosméticos masculinos, equipos de gimnasia, solárium y demás maquinaria estética para lograr un cuerpo atlético y bien acicalado, identificador material del éxito social.	Mary Harron	Christian Bale, Willem Dafoe, Jared Leto, Josh Lucas, Samantha Mathis, Matt Ross, Bill Sage, Chloë Sevigny, Cara Seymour, Justin Theroux, Guinevere Turner y Reese Witherspoon.	Lions Gate Films	Estados Unidos	6.6	https://www.youtube.com/embed/d1QmQsRD9_w?si=PkIOGXZccEb1NbYu
60	Karate Kid	https://play-lh.googleusercontent.com/whQVK8VDCyGWVBiWbxvzb9e00rifM4XfoKNq8Sag0FAABdFwzBQvGMyJmkDnOo2ne5IO	1984	Accion y Artes marciales.	126	Daniel Larusso llega a Los Ángeles de la costa este y enfrenta la difícil tarea de hacer nuevos amigos. Sin embargo, se convierte en el blanco del acoso de los Cobras, una amenazadora pandilla de estudiantes de karate, cuando inicia una relación con Ali, la ex novia del líder de los Cobras. Deseoso de defenderse e impresionar a su nueva novia, pero temeroso de enfrentar a la peligrosa pandilla, Daniel le pide a su conserje Miyagi, un maestro de las artes marciales, que le enseñe karate.	John G. Avildsen	Ralph Macchio, Noriyuki "Pat" Morita, Elisabeth Shue, William Zabka, Randee Heller y Cayetano Damian Badaracco.	Columbia Pictures	Estados Unidos	6.1	https://www.youtube.com/embed/xlnm0NtPoVs?si=L_gSb6wT0-sbqsbh
61	Karate Kid Parte 2	https://perdidaenmismundos.files.wordpress.com/2020/11/karate-kid-2-750.jpg?w=421	1986	Accion, Drama y Artes marciales.	113	Daniel acompaña a Miyagi a su tierra, Okinawa, y allí aprende cosas sobre el pasado secreto de su maestro. Para Miyagi, es la oportunidad de ver a su padre por última vez y de reanudar su romance con el amor de su infancia. Sin embargo, su regreso también reavivará su vieja enemistad con Sato y arrastrará a Daniel a un choque de culturas y combates donde el precio del honor es la propia vida.	John G. Avildsen	Ralph Macchio, Noriyuki  Morita, Danny Kamekona, Nobu McCarthy, Yuji Okumoto, Tamlyn Tomita y Martin Kove.	Columbia Pictures y Sony	Estados Unidos	4.9	https://www.youtube.com/embed/V-T0ajeo7xQ?si=8XP8pzOGKP3y2fZl
62	Karate Kid Parte 3	https://musicart.xboxlive.com/7/799b1100-0000-0000-0000-000000000002/504/image.jpg?w=1920&h=1080	1989	Accion, Drama y Artes marciales.	112	Daniel regresa de Okinawa con la esperanza de poder llevar una pacífica vida trabajando con su tutor Miyagi en su tienda de bonsáis. Sin embargo, la tranquilidad se ve truncada cuando es chantajeado para que compita contra Mike Barnes. Su maestro se niega a ayudarlo, así que el joven se busca otro entrenador, que resulta ser un hombre violento que sólo quiere formarlo para matar. Cuando Daniel se da cuenta de su error, intenta volver con Miyagi.	John G. Avildsen	Ralph Macchio, Noriyuki Morita, Robyn Lively, Sean Kanan, Randee Heller, Thomas Ian, Griffith y Martin Kove.	Columbia Pictures y Sony	Estados Unidos	4.2	https://www.youtube.com/embed/42xkTso8krA?si=7ImAAtmiNWxPGgVc
65	Matrix	https://i.pinimg.com/1200x/6d/2c/0b/6d2c0bb97c516125f196f08c34b0e14b.jpg	1999	Accion y Ciencia ficción.	136	El programador informático Thomas Anderson, más conocido en el mundo de los "hacker" como Neo, está en el punto de mira del temible agente Smith. Otros dos piratas informáticos, Trinity y Morfeo, se ponen en contacto con Neo para ayudarlo a escapar. Matrix te posee. Sigue al conejo blanco.	Hermanas Wachowski	Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss y Hugo Weaving.	Warner Bros. Pictures	Estados Unidos y Australia	7.9	https://www.youtube.com/embed/Pl_H2Lmjn6k?si=wyxrrCCGsBIhVhuy
66	Matrix Recargado	https://m.media-amazon.com/images/M/MV5BODE0MzZhZTgtYzkwYi00YmI5LThlZWYtOWRmNWE5ODk0NzMxXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg	2003	Accion y Ciencia ficción.	138	250.000 centinelas del Ejército de las Máquinas se dirigen hacia la ciudad oculta de Sión, último enclave de supervivencia de los humanos. Morfeo, Trinity y Neo disponen de 72 horas hasta que las máquinas lleguen al santuario humano. Las hermanas Lilly y Lana Wachowski alcanzarán una repercusión inesperada.	Hermanas Wachowski	Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss, Hugo Weaving, Monica Bellucci, Randall Duk Kim y Jada Pinkett Smith.	Warner Bros. Pictures	Estados Unidos y Australia	6.4	https://www.youtube.com/embed/dvauYuYX4Jc?si=2izJO6PuSJNNGAYB
22	Star Wars: Episode V - The Empire Strikes Back	https://i.ebayimg.com/images/g/GDEAAOSwo3pWgLdG/s-l1600.jpg	1980	Accion, Aventura, Space opera, Blockbuster y Ciencia ficción.	124	Son tiempos adversos para la rebelión. Aunque la Estrella de la Muerte ha sido destruida, las tropas imperiales han hecho salir a las fuerzas rebeldes de sus bases ocultas y los persiguen a través de la galaxia. Tras escapar de la terrible Flota Imperial, un grupo de guerreros de la libertad, encabezados por Luke Skywalker, ha establecido una nueva base secreta en el remonto mundo helado de Hoth.	George Lucas	Mark Hamill, Harrison Ford, Carrie Fisher, Peter Cushing, Alec Guinness, Anthony Daniels, Kenny Baker, Peter Mayhew, David Prowse, Jack Purvis, Eddie Byrne y James Earl Jones.	Lucasfilm	Estados Unidos	8.1	https://www.youtube.com/embed/JNwNXF9Y6kY?si=_37GQj37ZufOJFWQ
63	Karate Kid 4: La Nueva Aventura	https://es.web.img3.acsta.net/r_1280_720/medias/nmedia/18/79/76/01/19516910.jpg	1994	Accion, Drama y Artes marciales.	108	Durante una conmemoración en honor a los soldados japoneses que lucharon durante la Segunda Guerra Mundial, el señor Miyagi conoce a Julie. La joven perdió a sus padres cuando solo era una niña y ahora, a sus 17 años, se convierte en el objetivo de Alpha Elite, un grupo de disciplina militar de su instituto al que deberá aprender a hacer frente. Por ello, Miyagi decide enseñarle unas lecciones de kárate.	Christopher Cain	Hilary Swank, Noriyuki Morita, Michael Ironside, Constance Towers y Chris Conrad	Columbia Pictures y Sony	Estados Unidos	3.5	https://www.youtube.com/embed/5LNE7jk2QWY?si=iQDUQgcy0pp0hlNp
64	Karate Kid (2010)	https://play-lh.googleusercontent.com/Z_t3rQxsOr4UEDJpiMxfaTtWKR-20HhHKf7UXch3Fpt9q8PAxOykbH2rGeVxw73u9ZrL=w240-h480-rw	2010	Accion, Drama y Artes marciales.	140	Cuando la carrera profesional de su madre los lleva a China, Dre Parker, de 12 años, descubre que es un extraño en una tierra desconocida. A pesar de que él sabe un poco de karate, sus habilidades para pelear no son suficientes contra Cheng, el acosador de su escuela. Dre encuentra a un amigo en el Sr. Han, un empleado de mantenimiento que también es maestro de las artes marciales. El Sr. Han le enseña a Dre todo sobre kung fu con la esperanza de que venza a Cheng.	Harald Zwart	Jackie Chan, Jaden Smith y Taraji P. Henson.	Sony Pictures Home Entertainment	Estados Unidos, Canada y China	5.7	https://www.youtube.com/embed/Az-gd83z-JA?si=WX8OOHHUfwMwuYim
71	El Padrino	https://es.web.img3.acsta.net/pictures/22/01/13/16/56/0142706.jpg	1972	Drama, Crimen y Gánsteres	177	Don Vito Corleone es el respetado y temido jefe de una de las cinco familias de la mafia de Nueva York en los años 40. El hombre tiene cuatro hijos: Connie, Sonny, Fredo y Michael, que no quiere saber nada de los negocios sucios de su padre. Cuando otro capo, Sollozzo, intenta asesinar a Corleone, empieza una cruenta lucha entre los distintos clanes.	Francis Ford Coppola	Marlon Brando, Al Pacino, Robert Duvall, James Caan, Richard Castellano y Diane Keaton.	Paramount Pictures	Estados Unidos	9.0	https://www.youtube.com/embed/iOyQx7MXaz0?si=iNovsUWjwLBRcRkf
73	El padrino III	https://es.web.img3.acsta.net/medias/nmedia/18/68/09/69/20420487.jpg	1990	Drama, Crimen y Gánsteres	163	Michael Corleone, heredero del imperio de don Vito Corleone, intenta rehabilitarse socialmente y legitimizar todas las posesiones de la familia negociando con el Vaticano. Después de luchar toda su vida se encuentra cansado y centra todas sus esperanzas en encontrar a un sucesor que se haga cargo de los negocios.	Francis Ford Coppola	Al Pacino, Diane Keaton, Talia Shire y Andy García.	Paramount Pictures	Estados Unidos	7.8	https://www.youtube.com/embed/_LZJxPbzvOo?si=MfKl5mJfM684wjMp
75	Taxi Driver	https://m.media-amazon.com/images/M/MV5BM2M1MmVhNDgtNmI0YS00ZDNmLTkyNjctNTJiYTQ2N2NmYzc2XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_FMjpg_UX1000_.jpg	1976	Drama y Suspenso.	113	Ambientada en la Nueva York de la década de 1970, poco después de que terminara la guerra de Vietnam, se centra en la vida de Travis Bickle, un excombatiente solitario e inestable que debido a su insomnio crónico comienza a trabajar como taxista, se incorpora a la turbia vida nocturna de la ciudad.	Martin Scorsese	Robert De Niro, Jodie Foster, Albert Brooks, Harvey Keitel, Peter Boyle y Cybill Shepherd.	Columbia Pictures	Estados Unidos	8.2	https://www.youtube.com/embed/-yk9PSO7dFw?si=fj-aF1oByeDOuCcR
74	El padrino de Mario Puzo, epílogo: la muerte de Michael Corleone	https://i.blogs.es/653d70/el-padrino-3-epilogo-poster-trailer-opinion/450_1000.jpg	2020	Drama, Crimen y Gánsteres	162	Michael Corleone (Al Pacino) ya tiene 60 años, y solo quiere proteger a su familia del crimen que les rodea y encontrar al mejor sucesor para su emporio. Ese podría ser el vehemente Vincent (Andy García), pero también podría ser la chispa que convertiría la esperanza de Michael de tener una empresa legítima en un infierno de violencia.	Francis Ford Coppola	Al Pacino, Diane Keaton, Talia Shire, Andy García, Eli Wallach, Joe Mantegna, George Hamilton y Bridget Fonda.	Paramount Pictures	Estados Unidos	6.2	https://www.youtube.com/embed/JV59AdcpqEE?si=eeB1C_0WMLscSzbu
72	El padrino II	https://www.mubis.es/media/movies/400/26974/el-padrino-parte-ii-l_cover.jpg	1974	Drama, Crimen y Gánsteres	200	Tras la muerte de Don Vito Corleone, su hijo Michael es elegido para liderar los negocios familiares. El nuevo cabeza de familia debe lidiar con un panorama cambiante de amistades y enemistades, al tener que negociar con la mafia judía y perder el apoyo de Frankie. Al mismo tiempo, Michael escapa por los pelos de un atentado. Simultáneamente, se recuerda el ascenso y los orígenes de Don Vito en Sicilia y como inmigrante en Nueva York.	Francis Ford Coppola	Al Pacino, Robert Duvall, Diane Keaton, Robert De Niro, Talia Shire, Morgana King, John Cazale, Mariana Hill y Lee Strasberg.	Paramount Pictures	Estados Unidos	8.9	https://www.youtube.com/embed/Ts1lHOyWNSE?si=R8lWw0jAzlrkW-iX
77	Pulp fiction	https://musicart.xboxlive.com/7/767c6300-0000-0000-0000-000000000002/504/image.jpg?w=1920&h=1080	1994	Crimen y Humor negro	154	Jules Winnfield (Samuel L. Jackson, Jackie Brown) y Vincent Vega (John Travolta, Grease) son dos asesinos a sueldo que trabajan a las órdenes del temido gángster Marsellus Wallace (Ving Rhames, Amanecer de los muertos), quien les encarga la importante misión de recuperar su misterioso maletín, que ha sido robado.	Quentin Tarantino	John Travolta, Samuel L. Jackson, Uma Thurman, Harvey Keitel, Tim Roth, Amanda Plummer, Maria de Medeiros, Ving Rhames, Eric Stoltz, Rosanna Arquette, Christopher Walken y Bruce Willis.	Miramax Films	Estados Unidos	8.6	https://www.youtube.com/embed/r-PSxjTR174?si=-AaJfzR9GM9KiRY5
78	La vida es bella	https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSC1_dLC4UnFy-wm9zKIbmrWphQoCMRiNY2dg&s	1997	Drama y Cine belico	116	En 1939, a punto de estallar la Segunda Guerra Mundial, Guido llega a Arezzo con la intención de abrir una librería. Allí conoce a Dora y, a pesar de que está prometida con el fascista Rodolfo, acaba casándose con ella y tienen un hijo. Poco después de estallar la guerra, las tropas nazis llegan a Italia y los tres son internados en un campo de concentración. Allí, Guido construye una elaborada fantasía para proteger a su hijo y hacerle creer que la situación es tan solo un juego.	Roberto Benigni	Roberto Benigni, Nicoletta Braschi y Giorgio Cantarini.	Miramax Films	Italia	8.5	https://www.youtube.com/embed/8_TJRfXIoY4?si=fytOjBJBUi2B2cJw
80	Piratas del caribe: El cofre de la muerte	https://es.web.img3.acsta.net/pictures/14/03/25/11/14/498694.jpg	2006	Accion, aventura y comedia	151	Cuando el fantasmal pirata Davy Jones llega a cobrar una deuda sangrienta, el Capitán Jack Sparrow debe encontrar la forma de evitar su destino y que su alma sea maldecida para siempre. No obstante, el astuto fantasma logra interrumpir los planes nupciales de los amigos de Jack, Will Turner y Elizabeth Swann.	Gore Verbinski	Johnny Depp, Orlando Bloom, Keira Knightley, Stellan Skarsgard, Bill Nighy, Jack Davenport, Kevin R. McNally, Jonathan Pryce, Lee Arenberg, Mackenzie Crook, Tom Hollander, Naomie Harris, Alex Norton, David Bailie y Martin Klebba.	Walt Disney Pictures	Estados Unidos	6.4	https://www.youtube.com/embed/PsBz960lF2o?si=B08G-YNIRGt0TJP-
90	Deadpool	https://play-lh.googleusercontent.com/vdC-3zQ3K1133Qvcl-71O9ulLeu1IsehUWc_2phxEFfy3lo27R3LOa2rbr3xK5YUMY1s	2016	Acción, Superhéroes, Ciencia ficción, Comedia y Humor negro.	108	Wade Wilson, tras ser sometido a un cruel experimento científico, adquiere poderes especiales que le convierten en Deadpool. Armado con sus nuevas habilidades y un retorcido sentido del humor tratará de dar caza al hombre que casi destruye su vida.	Tim Miller	Ryan Reynolds, Morena Baccarin, Ed Skrein, T. J. Miller,Gina Carano, Leslie Uggams, Brianna Hildebrand y Stefan Kapičić.	20th Century Fox	Estados Unidos	6.8	https://www.youtube.com/embed/0JnRdfiUMa8?si=tkJ2T50P6F1magUU
82	Piratas del Caribe: Navegando en aguas misteriosas	https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p7989366_p_v8_ab.jpg	2011	Accion, aventura, fantasia y comedia	136	El capitán Jack Sparrow encuentra a una mujer de su pasado, quien lo obliga a subir al Barba Negra para emprender un viaje en busca de la legendaria Fuente de la Juventud.	Rob Marshall	Johnny Depp, Penélope Cruz, Ian McShane, Geoffrey Rush, Kevin R. McNally, Sam Claflin, Astrid Bergès-Frisbey, Stephen Graham, Richard Griffiths, Greg Ellis,Óscar Jaenada y Keith Richards.	Walt Disney Pictures	Estados Unidos	5.4	https://www.youtube.com/embed/rQgTpO9J0Bk?si=i-B_9CRhU7jYsgAg
81	Piratas del Caribe: En el fin del mundo	https://m.media-amazon.com/images/S/pv-target-images/7ce5e2a212c4d1265c35a75cdc73fdbc51ef60472a4c7b46cf02b7e26e755c0b.jpg	2007	Accion, aventura, fantasia y comedia	168	Will Turner (Orlando Bloom) y Elizabeth Swann (Keira Knightley) unen fuerzas con el Capitán Barbossa (Geoffrey Rush) para liberar a Jack Sparrow (Johnny Depp) del encierro de Davy Jones. Mientras tanto, la tripulación del barco fantasma El Holandés Volador causa estragos en los Siete Mares. Los amigos deben navegar a través de aguas peligrosas para enfrentarse al pirata chino Sao Feng (Chow Yun-Fat) y, finalmente, ellos deben decidir un lado de la batalla cuando está en juego la vida del pirata.	Gore Verbinski	Johnny Depp, Orlando Bloom, Keira Knightley, Geoffrey Rush, Bill Nighy, Stellan Skarsgard, Chow Yun-Fat, Kevin R. McNally, Naomie Harris, Tom Hollander, Jack Davenport y Jonathan Pryce.	Walt Disney Pictures	Estados Unidos	6.1	https://www.youtube.com/embed/ZM7YGqyosgo?si=aOAAQ2RplyA28PRq
84	Indiana Jones y los cazadores del arca perdida	https://play-lh.googleusercontent.com/NIuel5FmAXuJ7iJRmG0mN8Bogw_RUwzpDqVppAX6iZIjcbCXIPLhoJ4md3LJm5g2obk30y0zvcENtWUt-As=w240-h480-rw	1981	Aventura, Acción, Histórico y Sobrenatural.	115	Después de una infructuosa misión en Sudamérica, el Gobierno estadounidense encarga al arqueólogo Indiana Jones la búsqueda del Arca de la Alianza, una reliquia bíblica que contiene los diez mandamientos y que convierte en invencible a su portador. Jones deberá enfrentarse a los nazis para adquirir este precioso objeto.	Steven Spielberg	Harrison Ford, Karen Allen, Paul Freeman, Ronald Lacey, John Rhys-Davies, Denholm Elliott, Alfred Molina, Wolf Kahler, Anthony Higgins, Vic Tablian, Pat Roach, Don Fellows y William Hootkins.	Lucasfilm	Estados Unidos	7.8	https://www.youtube.com/embed/htHMMjfefYE?si=MQZZBdVmk5Iw7j2K
83	Piratas del caribe: La venganza de Salazar	https://es.web.img3.acsta.net/pictures/17/03/27/17/40/153012.jpg	2017	Accion, aventura, fantasia y comedia	129	El capitán Salazar comanda un ejército de piratas fantasma con el que pretende exterminar a todos los piratas vivos de la Tierra, pero Jack Sparrow se opone a él y busca el Tridente de Poseidón, un objeto mágico que permite a quien lo posee controlar los mares, la única esperanza para detener a Salazar.	Joachim Rønning	Johnny Depp, Javier Bardem, Geoffrey Rush, Brenton Thwaites, Kaya Scodelario, Kevin McNally, Keira Knightley y Orlando Bloom.	Walt Disney Pictures	Estados Unidos	5.4	https://www.youtube.com/embed/tETuAqWV9YY?si=FVSp6W33BiIjins0
86	Indiana Jones y la última cruzada	https://play-lh.googleusercontent.com/JGlejPcBrNAl32744ODRf6UDMQamJw5PbEm1ix1DU-DIfj8TAUEg-YpwUKMBo8ZH4GQ=w240-h480-rw	1989	Aventura, Acción, Histórico y Sobrenatural.	118	El intrépido explorador Indiana Jones tiene que rescatar a su padre, un arqueólogo que ha desaparecido mientras buscaba el Santo Grial. Siguiendo las pistas de la libreta de su padre, Indiana llega a Venecia, donde recibe la ayuda de una profesora especialista. Los dos intentarán rescatar a Henry Jones y, de paso, hacerse con la preciada reliquia, que también quieren los nazis.	Steven Spielberg	Harrison Ford, Sean Connery, Denholm Elliott, Alison Doody, John Rhys-Davies, Julian Glover, River Phoenix, Michael Byrne, Kevork Malikyan, Robert Eddison, Richard Young y Alexei Sayle.	Lucasfilm	Estados Unidos	7.8	https://www.youtube.com/embed/OSYMxkLznPs?si=dx13U6hy37pCz_Dz
87	Indiana Jones y el reino de la calavera de cristal	https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTLEI1VjQVGem5FT9iDgPpvaUtf5mgRNdDOvQ&s	2008	Aventura, Acción, Histórico y Sobrenatural.	123	Indiana conoce a Mutt, un joven rebelde que le propone un trato: si le ayuda a resolver un problema personal, él, a cambio, le facilitaría uno de los descubrimientos más espectaculares de la historia: la Calavera de Cristal de Akator, que se encuentra en un lugar remoto del Perú.	Steven Spielberg	Harrison Ford, Cate Blanchett, Shia LaBeouf, Ray Winstone, Karen Allen, John Hurt y Jim Broadbent.	Lucasfilm	Estados Unidos	5.4	https://www.youtube.com/embed/b3J5uCi-ygU?si=QlETCaKBpmk2ee4_"
88	Indiana Jones y el llamado del destino	https://pics.filmaffinity.com/Indiana_Jones_y_el_dial_del_destino-145866922-large.jpg	2023	Aventura, Acción, Histórico y Sobrenatural.	154	En 1969, un Indiana Jones envejecido y derrotado por la vida regresa a la acción para evitar que la hija de uno de sus amigos venda un artilugio que permite viajar en el tiempo a unos nazis que pretenden alterar el curso de la Segunda Guerra Mundial.	Steven Spielberg	Harrison Ford, Phoebe Waller-Bridge, Mads Mikkelsen, John Rhys-Davies y Antonio Banderas.	Walt Disney Pictures	Estados Unidos	6.2	https://www.youtube.com/embed/PR299S5zAnU?si=nZq2kwmWuFKuZ9Ss
89	Bastardos sin gloria	https://www.tematika.com/media/catalog/Ilhsa/Imagenes/628473.jpg	2009	Cine Bélico, drama, acción, comedia y humor negro	153	Shosanna, una judia en la Fracia ocupada por los nazis, presencia la ejecución de su familia por orden del coronel nazi, Hans Landa. Huye a Paris y adopta una nueva identidad como propietaria de un cine. Mientras el teniente Aldo Raine adiestra a un grupo de soldados judíos. Los hombres de Raine y una actriz alemana que agente doble, deben llevar a cabo una misión que hará caer a los jefes del Tercer Reich. El destino quiere que todos se encuentren bajo la marquesina de un cine donde Shosanna espera para vengarse.	Quentin Tarantino	Brad Pitt, Christoph Waltz, Mélanie Laurent, Eli Roth, Diane Kruger, Daniel Brühl, Til Schweiger y Michael Fassbender.	Universal Pictures	Estados Unidos	7.8	https://www.youtube.com/embed/9spvI1O9xPA?si=BpZc4liNyTn28tmw
93	Rambo: Primera sangre - Parte II	https://m.media-amazon.com/images/M/MV5BZWFkY2I1ZDAtNmZhNS00NjVlLWJiMGQtMGQ1ZmM0ZDA5ODg5XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg	1985	Acción.	96	El ex Boina Verde John Rambo,es liberado de la cárcel por el coronel Troutman para que le ayude en la búsqueda de prisioneros de guerra americanos en el sureste de Asia.	George P. Cosmatos	Sylvester Stallone, Richard Crenna, Charles Napier y Stephen Berkoff.	Carolco Pictures	Estados Unidos	5.6	https://www.youtube.com/embed/jtPNhGWxY4g?si=PLHz1twsUG6MG_SJ
94	Rambo III	https://es.web.img3.acsta.net/medias/nmedia/18/79/16/35/20148228.jpg	1988	Acción.	101	El coronel Trautman pide ayuda a Rambo para combatir la invasión soviética de Afganistán. El soldado, ahora budista, rechaza la petición, pero, poco después, le informan que los soviéticos han secuestrado a Trautman.	Peter MacDonald	Sylvester Stallone, Richard Crenna y Kurtwood Smith.	Carolco Pictures	Estados Unidos	4.8	https://www.youtube.com/embed/nY-ZMsmGmEU?si=JiELYpaqvuO668Mr
91	Deadpool 2	https://es.web.img3.acsta.net/pictures/18/04/26/11/50/5029006.jpg	2018	Acción, Superhéroes, Ciencia ficción, Comedia y Humor negro.	119	Deadpool trabaja ahora a escala internacional, eliminando a asesinos de masas, gánsteres, traficantes de personas y demás indeseables. Se creen intocables, pero Deadpool sabe cómo deshacerse de ellos de la forma más complicada, desmedida y sangrienta posible.	David Leitch	Ryan Reynolds, Josh Brolin, Morena Baccarin, Julian Dennison, Zazie Beetz, T. J. Miller, Brianna Hildebrand, Jack Kesy, Hugh Jackman, Terry Crews y Brad Pitt.	20th Century Fox	Estados Unidos	6.7	https://www.youtube.com/embed/4i6ZePa8jz4?si=ew8KDkzvRLKyU1Rb
92	Rambo: Primera sangre	https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-TIUuDhXDsWLTW11TqzElAnkBbsyJNBpqDA&s	1982	Acción.	97	John Rambo es un veterano boina verde que luchó en Vietnam. Un día va a visitar a un viejo amigo del ejército pero se entera de que ha muerto. Algunos días después, la policía lo detiene por vagabundo y se enseña con él. En ese momento, John recuerda los terrores y las torturas que sufrió durante la guerra de Vietnam y reacciona violentamente.	Ted Kotcheff	Sylvester Stallone, Richard Crenna, Brian Dennehy, David Caruso, Jack Starrett, Bill McKinney, Alf Humphreys, Patrick Stack, John McLiam y Danny Vozna.	Orion Pictures Corporation	Estados Unidos y Canada	6.6	https://www.youtube.com/embed/oXngES_l_HQ?si=nXvmr-9yqFgYp7to
95	Rambo IV: EL regreso al infierno	https://i.pinimg.com/736x/1d/5f/08/1d5f08c5badabaddc6402dcbdceac700.jpg	2008	Acción.	92	El ex boina verde John Rambo lleva una solitaria y apacible vida en la jungla del norte de Tailandia, pescando y cazando cobras para venderlas. Todo cambia cuando un grupo de misioneros católicos le proponen que les sirva de guía hasta la frontera con Birmania para suministrar medicinas y alimentos a los refugiados asediados por el ejército birmano, que ha hecho de la tortura y el asesinato una práctica habitual. En estas circunstancias, Rambo no tendrá más remedio que volver a tomar partido.	Sylvester Stallone	Sylvester Stallone, Julie Benz y Matthew Marsden.	Lionsgate	Estados Unidos	5.4	https://www.youtube.com/embed/2CRjdwRYQbU?si=GAsxRpUiEnoEjDQw
96	Rambo V: La última misión	https://www.ubuy.com.ar/productimg/?image=aHR0cHM6Ly9tLm1lZGlhLWFtYXpvbi5jb20vaW1hZ2VzL0kvOTEwS2lqcTVsb0wuX1NMMTUwMF8uanBn.jpg	2019	Acción.	89	John Rambo está en horas bajas y viviendo en un rancho en Arizona, pero cuando recibe la noticia de que su nieta ha desaparecido, tras haber cruzado la frontera a México para ir a una fiesta, Rambo decide ir en su búsqueda.	Adrian Grunberg	Sylvester Stallone, Paz Vega, Sergio Peris-Mencheta, Adriana Barraza, Yvette Monreal, Joaquín Cosío y Óscar Jaenada.	Lionsgate	Estados Unidos	5.5	https://www.youtube.com/embed/TYBISLzhhdY?si=2G09BWmxKZjiULpS
97	El lobo de Wall Street	https://es.web.img3.acsta.net/pictures/210/615/21061596_20131129121836144.jpg	2013	Sátira, Drama, Humor negra, Crimen y Biográfica..	180	La historia del corredor de bolsa neoyorquino Jordan Belfort, quien, con poco más de veinte años, fue apodado "El lobo de Wall Street" por su enorme éxito y fortuna como fundador de la agencia bursátil Stratton Oakmont	Martin Scorsese	Leonardo DiCaprio, Jonah Hill, Margot Robbie, Matthew McConaughey, Kyle Chandler, Rob Reiner, Jon Bernthal, Jon Favreau y Jean Dujardin.	Paramount Pictures	Estados Unidos	7.6	https://www.youtube.com/embed/PaAvUOXUohk?si=J17_bU-Mc6VelZYF
98	Rango	https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRPP9jb8bZkrnCG40R8PaWBgTHtG9Mxtij2uw&s	2011	Animación, Acción, Comedia y Western.	107	Rango es un camaleón que lleva toda su vida viviendo como mascota en un terrario, mirando cómo pasa el mundo a través del cristal. Sin embargo, un buen día cuando transportan su terrario, éste se cae del coche que lo transportaba en medio del desierto de Mojave. Rango acaba en un pueblo salvaje llamado Polvo, un lugar peligroso habitado por criaturas extrañas. Sin pretenderlo, Rango se convierte en el "Sheriff".	Gore Verbinski	Johnny Depp, Isla Fisher, Abigail Breslin, Alfred Molina, Bill Nighy, Harry Dean Stanton, Ray Winstone, Timothy Olyphant, Ned Beatty , Gil Birmingham, Blake Clark, James Ward Byrkit, Claudia Black y Stephen Root.	Paramount Pictures	Estados Unidos	6.4	https://www.youtube.com/embed/Kn-G23gRQwg?si=56fu4zH7M8TBq_Ld
99	Scareface	https://palomaynacho-1f321.kxcdn.com/wp-content/uploads/2023/12/scarface-reestreno-poster-jpg.webp	1983	crimen, drama y gánsteres	170	Tony Montana es un emigrante cubano frío y sanguinario que se instala en Miami con el propósito de convertirse en un gángster importante. Con la colaboración de su amigo Manny Rivera inicia una fulgurante carrera delictiva con el objetivo de acceder a la cúpula de una organización de narcos.	Brian De Palma	Al Pacino, Steven Bauer, Michelle Pfeiffer, Mary Elizabeth Mastrantonio, Robert Loggia, Míriam Colón, F. Murray Abraham, Paul Shenar, Harris Yulin y Ángel Salazar	Universal Pictures	Estados Unidos	8.2	https://www.youtube.com/embed/RNsaQak_HfY?si=8OP6IL6gIyUNNH8s
101	X-Men 2	https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSrcKNDiRCWJxhsx9aiAtCUr3qQSkwc8qHEYQ&s	2003	Superhéroes, Acción y Ciencia ficción.	133	Un mutante desconocido se introduce en la Casa Blanca e intenta asesinar al presidente sin éxito. Charles Xavier y el resto de mutantes intentan hallar su paradero para capturarlo.	Bryan Singer	Patrick Stewart, Hugh Jackman, Ian McKellen, Halle Berry, Famke Janssen, James Marsden, Rebecca Romijn, Brian Cox, Alan Cumming, Bruce Davison, Shawn Ashmore, Aaron Stanford, Kelly Hu y Anna Paquin.	20th Century Fox	Estados Unidos	6.4	https://www.youtube.com/embed/luHcOYS1HxQ?si=7_a0cGGnDeQOSt2z
111	La odisea de los giles	https://pics.filmaffinity.com/La_odisea_de_los_giles-274529633-large.jpg	2019	Drama y Aventura	116	Un grupo de vecinos se organiza para llevar a cabo un provecto que ayude a paliar la crisis. Sin embargo en medio de este corralito en el que son víctimas de un abogado y un banquero, se organizarán para planear cómo recuperar sus ahorros.	Sebastián Borensztein	Ricardo Darín, Luis Brandoni, Chino Darín, Verónica Llinás, Daniel Aráoz, Carlos Belloso, Rita Cortese, Andrés Parra, Marco Antonio Caponi, Alejandro Gigena y Guillermo Jacubowicz.	Mod Producciones	Argentina	6.6	https://www.youtube.com/embed/ZP_o6GQaFW8?si=g3dNSa8XgnLAZ5Ge
79	Piratas del Caribe: La maldición del Perla Negra	https://es.web.img3.acsta.net/medias/nmedia/18/91/06/54/20129011.jpg	2003	Accion, aventura y comedia	143	El capitán Barbossa le roba el barco al pirata Jack Sparrow y secuestra a Elizabeth, amiga de Will Turner. Barbossa y su tripulación son víctimas de un conjuro que los condena a vivir eternamente y a transformarse cada noche en esqueletos vivientes.	Gore Verbinski	Johnny Depp, Geoffrey Rush, Orlando Bloom, Keira Knightley, Jack Davenport,Kevin R. McNally, Zoe Saldaña, Jonathan Pryce,Treva Etienne, Lee Arenberg, Mackenzie Crook, Trevor Goddard, Isaac C. Singleton Jr y Brye Cooper.	Walt Disney Pictures	Estados Unidos	7.2	https://www.youtube.com/embed/tnx35Z4nWWc?si=N9somDe42DIcT6kH
85	Indiana Jones y el templo de la perdición	https://pics.filmaffinity.com/indiana_jones_and_the_temple_of_doom-721053273-large.jpg	1984	Aventura, Acción, Histórico y Sobrenatural.	118	En Shanghái, Indiana Jones se mete en un lío con unos gánsters que compiten por una joya. Finalmente consigue escapar del lugar con una bella cantante y su joven acompañante. Los tres escapan en una avioneta que, tras un accidentado vuelo, aterriza en el corazón de la India. Allí intentarán ayudar a los habitantes de un pequeño poblado que ha quedado devastado después del robo de una joya sagrada con poderes.	Steven Spielberg	Harrison Ford, Kate Capshaw, Jonathan Ke Quan, Amrish Puri, Roshan Seth y Philip Stone.	Lucasfilm	Estados Unidos	7.4	https://www.youtube.com/embed/zJGuaqiTxUM?si=2t7-mYOtkAMc2g2G
28	Kung Fu Panda 2	https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRZ0yMKXSKU1oqd6qEdbyfjyzmTS_5ZqsElNw&s	2011	Animación, Aventura, Comedia y Acción.	90	Ahora conocido como el Dragón Guerrero, Po protege el Valle de la Paz junto con sus amigos y compañeros maestros de kung fu, los Cinco Furiosos. Sin embargo, un peligroso villano amenaza la nueva e impresionante vida de Po con planes para usar un arma secreta para desaparecer el arte marcial y conquistar China. Con el fin de derrotar a su nuevo enemigo, Po tiene que recordar su pasado y desbloquear secretos de sus misteriosos orígenes.	Jennifer Yuh Nelson	Jack Black, Jackie Chan, Dustin Hoffman, Angelina Jolie, Seth Rogen, Ian McShane, Lucy Liu, David Cross, James Hong, Gary Oldman, Michelle Yeoh, Jean-Claude Van Damme y Victor Garber.	DreamWorks Animation	Estados Unidos	6.2	https://www.youtube.com/embed/FQ63rqSRrEI?si=reczqQ82iuTlPu_c
49	Los juegos del hambre	https://i.pinimg.com/736x/52/d6/5d/52d65d59c4d9613aa66790f230d7e01d.jpg	2012	Ciencia ficción, Acción, Drama y Distopía	142	Para demostrar su poder, el régimen del estado totalitario de Panem organiza cada año "Los juegos del hambre". En ellos, 24 jóvenes compiten el uno contra el otro en una batalla en la que solo puede haber un superviviente. La joven Katniss se ofrece voluntaria para participar en los juegos para salvar a su hermana. Junto a ella participará Peeta, un joven al que ha conocido desde la infancia y que está enamorado de ella. Sin embargo, el Capitolio quiere convertirlos en contrincantes.	Gary Ross	Jennifer Lawrence, Josh Hutcherson, Liam Hemsworth, Woody Harrelson, Elizabeth Banks, Lenny Kravitz, Stanley Tucci, Donald Sutherland, Alexander Ludwig, Isabelle Fuhrman, Amandla Stenberg	Warner Bros Pictures.	Estados Unidos	6.2	https://www.youtube.com/embed/_8Ktfs2mBDY?si=5PnejCwgwk0cF5XB
56	Titanic	https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSqJPTUUxybY2fILEB6wzW_bZN8-OwY5FIvLA&s	1997	Romance y Drama.	195	Jack es un joven artista que gana un pasaje para viajar a América en el Titanic, el transatlántico más grande y seguro jamás construido. A bordo del buque conoce a Rose, una chica de clase alta que viaja con su madre y su prometido Cal, un millonario engreído a quien solo interesa el prestigio de la familia de su prometida. Jack y Rose se enamoran a pesar de las trabas que ponen la madre de ella y Cal en su relación. Mientras, el lujoso transatlántico se acerca a un inmenso iceberg.	James Cameron	Leonardo DiCaprio, Kate Winslet, Billy Zane, Gloria Stuart, Bill Paxton, Kathy Bates, Frances Fisher, Victor Garber, Bernard Hill, Jonathan Hyde, David Warner, Bernard Fox, Danny Nucci y Ioan Gruffudd.	20th Century Fox	Estados Unidos	6.8	https://www.youtube.com/embed/tA_qMdzvCvk?si=430SEd15njGr3y01
76	La isla siniestra	https://mx.web.img3.acsta.net/c_310_420/pictures/18/10/14/05/09/3152154.jpg	2010	Terror, suspenso, drama, crímenes y misterio	138	Ambientada en 1954, los agentes judiciales Teddy Daniels y Chuck Aule son enviados a una remota isla del puerto de Boston para investigar la desaparición de una peligrosa asesina recluida en el hospital psiquiátrico Ashecliffe, un centro penitenciario para criminales perturbados dirigido por el siniestro doctor John Cawley. Pronto descubrirán que el centro guarda muchos secretos y que la isla esconde algo más peligroso que los pacientes.	Martin Scorsese	Leonardo DiCaprio, Mark Ruffalo, Ben Kingsley, Michelle Williams, Patricia Clarkson, Max von Sydow, Emily Mortimer, Jackie Earle Haley, Ted Levine, John Carroll Lynch, Elias  Koteas, Robin Bartlett, Christopher Denham, Joseph Sikora, Ruby Jerins, Jill Larson, Aidan Mitchell y Curtiss Cook.	Paramount Pictures y Columbia Pictures	Estados Unidos	7.6	https://www.youtube.com/embed/CRdakyXEZos?si=0fUKbDJ0eFpRjsYf
100	X-Men	https://m.media-amazon.com/images/M/MV5BZmIyMDk5NGYtYjQ5NS00ZWQxLTg2YzQtZDk1ZmM4ZDBlN2E3XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg	2000	Superhéroes, Acción y Ciencia ficción.	104	Los X-Men son seres que poseen increíbles y peligrosos poderes que derivan de extraordinarias mutaciones genéticas. Bajo la tutela del profesor Xavier, sus poderes son puestos al servicio del bien. Ahora deberán proteger al mundo de Magneto.	Bryan Singer	Patrick Stewart, Hugh Jackman, Ian McKellen, Halle Berry, Famke Janssen, James Marsden, Bruce Davison, Rebecca Romijn, Ray Park, Tyler Mane y Anna Paquin.	20th Century Fox	Estados Unidos	6.5	https://www.youtube.com/embed/1GnTdQPukYg?si=ih886bSrY9kYqerM
102	X-Men 3: La batalla final	https://m.media-amazon.com/images/M/MV5BNDBhNDJiMWEtOTg4Yi00NTYzLWEzOGMtMjNmNjAxNTBlMzY3XkEyXkFqcGdeQXVyNTIzOTk5ODM@._V1_.jpg	2006	Superhéroes, Acción y Ciencia ficción.	104	El descubrimiento de una cura para las mutaciones divide la situación en dos bandos. Los mutantes pueden elegir abandonar sus poderes y convertirse totalmente en humanos o continuar con sus habilidades y seguir aislados. Una guerra entre los seguidores de Charles Xavier, quien pregona la tolerancia, y los partidarios de Magneto, quien se inclina por la ley del más fuerte.	Brett Ratner	Hugh Jackman, Halle Berry, Ian McKellen, Famke Janssen, Anna Paquin, Kelsey Grammer, James Marsden, Rebecca Romijn, Shawn Ashmore, Aaron Stanford, Vinnie Jones y Patrick Stewart.	20th Century Fox	Estados Unidos	6.0	https://www.youtube.com/embed/vXs5gtdThYU?si=-Sl6CE-mnpglCd3r
103	X-Men Orígenes: Wolverine	https://m.media-amazon.com/images/M/MV5BZWRhMzdhMzEtZTViNy00YWYyLTgxZmUtMTMwMWM0NTEyMjk3XkEyXkFqcGdeQXVyNTIzOTk5ODM@._V1_.jpg	2009	Superhéroes, Acción y Ciencia ficción.	107	Nacido como mutante en 1845, Lobezno y su hermano huyen de su pueblo para inscribirse en el ejército, luchando en cada gran batalla americana. Un día son reclutados por el coronel Stryker para formar un ejército especial de mutantes. Lobezno acaba escapando e intenta seguir con una vida normal. Sin embargo, cuando descubre que Stryker le persigue se prepara para atacar de nuevo.	Gavin Hood	Hugh Jackman, Liev Schreiber, Danny Huston, Lynn Collins, Taylor Kitsch y Ryan Reynolds.	20th Century Fox	Estados Unidos	6.0	https://www.youtube.com/embed/lAd9dtKN7fk?si=hrRG2ZDLl2Dno0eZ
104	X-Men: primera generación	https://m.media-amazon.com/images/M/MV5BMTg5OTMxNzk4Nl5BMl5BanBnXkFtZTcwOTk1MjAwNQ@@._V1_FMjpg_UX1000_.jpg	2011	Superhéroes, Acción y Ciencia ficción.	132	A principios de los años 60, Charles y Erik, dos jóvenes de grandes habilidades y orígenes distintos, se hacen grandes amigos y se unen para proteger al mundo de una guerra nuclear.	Matthew Vaughn	James McAvoy, Michael Fassbender, Jennifer Lawrence, Nicholas Hoult, January Jones, Rose Byrne, Kevin Bacon y Zoe Kravitz.	20th Century Fox	Estados Unidos	6.8	https://www.youtube.com/embed/gEk93k7qOhU?si=hc-3kT_IKTYur8Gj
105	Wolverine: Inmortal	https://static.wikia.nocookie.net/xmen9260/images/2/28/Wolverine_Inmortal_alternativo.jpg/revision/latest?cb=20170223215550&path-prefix=es	2013	Superhéroes, Acción y Ciencia ficción.	138	Logan consigue salvarse y rescata a un oficial japonés, de la explosion de la bomba nuclear en Hiroshima. Años mas adelante, este oficial mandará a una joven a localizarlo. Logan se deberá enfrentar a un samurai de acero, mientras en su interior se lucha contra su propia inmortalidad.	James Mangold	Hugh Jackman, Tao Okamoto, Rila Fukushima, Hiroyuki Sanada, Svetlana Khodchenkova, Will Yun Lee, Famke Janssen, Haruhiko Yamanouchi y Brian Tee.	20th Century Fox	Estados Unidos	5.3	https://www.youtube.com/embed/ctPXSwPXqPQ?si=dpKxixdu-G-w4ZIi
106	X-Men: Días del futuro pasado	https://es.web.img2.acsta.net/pictures/14/04/30/15/56/008969.jpg	2014	Superhéroes, Acción y Ciencia ficción.	149	En el futuro, los mutantes luchan por sobrevivir en campos de concentración controlados por los terribles Centinelas de Industrias Trask. Para evitar ese mundo apocalíptico, los bandos de Charles Xavier y Magneto deberán unir fuerzas, enviando a logan al pasado para alterar la linea temporal y asi evitar su presente	Bryan Singer	Hugh Jackman, James McAvoy, Michael Fassbender, Jennifer Lawrence, Halle Berry, Nicholas Hoult, Anna Paquin, Elliot Page, Peter Dinklage, Shawn Ashmore, Omar Sy, Ian McKellen y Patrick Stewart.	20th Century Fox	Estados Unidos	6.9	https://www.youtube.com/embed/PXiv7velJNw?si=ggdQoM1bhhzeSP3U
107	X-Men: Apocalipsis	https://m.media-amazon.com/images/M/MV5BMjU1ODM1MzYxN15BMl5BanBnXkFtZTgwOTA4NDE2ODE@._V1_.jpg	2016	Superhéroes, Acción y Ciencia ficción.	144	En Sabah Nur ,Egipto, un mutante con un poder más allá de lo imaginable y venerado como un dios por su pueblo, se prepara para lograr vivir eternamente gracias a un nuevo e indestructible cuerpo. Sin embargo, en medio de la transferencia, En Sabah Nur y sus cuatro acólitos son enterrados vivos por quienes lo consideran un falso dios.	Bryan Singer	James McAvoy, Michael Fassbender, Jennifer Lawrence, Rose Byrne, Oscar Isaac, Nicholas Hoult, Evan Peters, Tye Sheridan, Sophie Turner, Olivia Munn y Lucas Till.	20th Century Fox	Estados Unidos	5.9	https://www.youtube.com/embed/lRRHaahnUSo?si=3e2WA46FAzpGWwpI
109	X-Men: Dark Phoenix	https://m.media-amazon.com/images/M/MV5BMmZmYTgwZGItNDIxMS00MmRkLWEzODQtYTllNzM0ZWE1NmQ5XkEyXkFqcGdeQXVyODQzNTE3ODc@._V1_.jpg	2019	Acción, Ciencia ficción y Superhéroes.	114	Los X-Men se enfrentan a su enemigo más poderoso: uno de sus miembros, Jean Grey. Durante una misión de rescate en el espacio, Jean casi muere al ser alcanzada por una misteriosa fuerza cósmica. Cuando regresa a casa, esa radiación la ha hecho más poderosa, pero mucho más inestable. Jean cae en una espiral fuera de control haciendo daño a aquellos que más quiere.	Simon Kinberg	James McAvoy, Michael Fassbender, Jennifer Lawrence, Nicholas Hoult, Sophie Turner, Tye Sheridan, Alexandra Shipp, Evan Peters, Kodi Smit-McPhee, Jessica Chastain, Scott Shepherd, Ato Essandoh, Halston Sage, Lamar Johnson, Hannah Anderson, Andrew Stehlin y Kota Eberhardt.	20th Century Fox	Estados Unidos	5.0	https://www.youtube.com/embed/jedZ6Wet5cI?si=M6ffca88g-4Uvzio
108	Logan	https://www.aceprensa.com/wp-content/uploads/2019/12/263115-0-scaled.jpg	2017	Superhéroes, Acción y Drama.	137	Han pasado los años y los mutantes están en declive. Logan, débil y cansado, vive alejado de todos hasta que acepta una última misión de Charles Xavier: la de proteger a una joven especial, de nombre Laura Kinney pero conocida como X-23, la última esperanza de la raza mutante.	James Mangold	Hugh Jackman, Patrick Stewart, Dafne Keen, Stephen Merchant, Boyd Holbrook, Richard E. Grant, Elizabeth Rodríguez y Eriq La Salle.	20th Century Fox	Estados Unidos	6.9	https://www.youtube.com/embed/atu1yOOXIz0?si=ReCSi3UEq2L5yHT9
110	El Clan	https://www.aceprensa.com/wp-content/uploads/2015/11/352161-0.jpg	2015	Drama, Bibliografica y Policial	110	Hacia afuera la familia de los Puccio guarda una apariencia discreta. No obstante, tras la aparente normalidad el clan de los Puccio es una familia sin escrúpulos que asegura sus ingresos a base de secuestros y extorsiones. Por un lado, Arquímedes, el patriarca, lidera las operaciones, mientras que Alejandro, el hijo mayor, se sirve de su popularidad para no levantar sospechas. Solo cuando Alejandro muestra sus dudas por las prácticas de su familia, el patriarca pierde la compostura.	Pablo Trapero	Guillermo Francella, Peter Lanzani, Lili Popovich y Gastón Cocchiarale.	Kramer & Sigman Films	Argentina	6.7	https://www.youtube.com/embed/Xdpb7obyt30?si=yzJ4HAZOe6Qziq-n
113	Metegol	https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTNJ1SJotZlF-Hzq3zDfvAgJ3gpavlJud_rJQ&s	2013	Animación, Aventuras, Comedia y Infantil.	106	Amadeo es un chico tímido y virtuoso que deberá enfrentarse a un habilidoso rival sobre el campo de fútbol, conocido con el apodo de El Crack. Para ello, contará con la inestimable ayuda de unos jugadores de futbolín liderados por el Wing, un carismático extremo derecho. Las aventuras de Amadeo y los jugadores tendrán como telón de fondo no solo el fútbol, sino también el amor, la amistad y la pasión.	Juan José Campanella	David Masajnik, Pablo Rago, Miguel Ángel Rodríguez, Fabián Gianola, Horacio Fontova, Sebastián Mogordoy, Diego Ramos y Coco Sily.	Antena 3 Films	Argentina	5.7	https://www.youtube.com/embed/QVhf5ucMhNc?si=XN2FhBrPr0Jx_M-D
114	La sociedad de la nieve	https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTHCnAexr4yuBJI9e5pPu2jgrS0LpcZGSdXtQ&s	2024	Aventuras, biográfico, drama, histórico y suspenso	144	En 1972, un vuelo procedente de Uruguay se estrella en un glaciar en los Andes. Solo 29 de sus 45 pasajeros sobreviven al accidente. Atrapados en uno de los entornos más hostiles del planeta, se ven obligados a luchar por sus vidas.	Juan Antonio Bayona	Enzo Vogrincic, Matías Recalt, Agustín Pardella, Felipe González Otaño, Luciano Chatton, Valentino Alonso, Francisco Romero, Agustín Berruti, Andy Pruss, Manuela Olivera, Simón Hempe y Juan Caruso.	El Arriero Films	España	7.6	https://www.youtube.com/embed/l9tP4M8URhQ?si=PJTKKBuj1Tzdp3Ps
\.


--
-- Name: catalogo catalogo_pkey; Type: CONSTRAINT; Schema: public; Owner: joacoeze
--

ALTER TABLE ONLY public.catalogo
    ADD CONSTRAINT catalogo_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

