--
-- PostgreSQL database dump
--

-- Dumped from database version 14.12 (Ubuntu 14.12-0ubuntu0.22.04.1)
-- Dumped by pg_dump version 14.12 (Ubuntu 14.12-0ubuntu0.22.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: catalogo; Type: TABLE; Schema: public; Owner: joacoeze
--

CREATE TABLE public.catalogo (
    id integer NOT NULL,
    nombre_de_pelicula character varying(100),
    url_imagen character varying(400),
    "año_de_estreno" integer,
    genero character varying(100),
    duracion integer,
    sinopsis character varying(1000),
    director character varying(200),
    actores_principales text,
    productora character varying(100),
    pais_de_origen character varying(100),
    puntaje_segun_critica numeric(2,1),
    url_trailer text
);


ALTER TABLE public.catalogo OWNER TO joacoeze;

--
-- Data for Name: catalogo; Type: TABLE DATA; Schema: public; Owner: joacoeze
--

COPY public.catalogo (id, nombre_de_pelicula, url_imagen, "año_de_estreno", genero, duracion, sinopsis, director, actores_principales, productora, pais_de_origen, puntaje_segun_critica, url_trailer) FROM stdin;
1	Batman: begins	https://es.web.img2.acsta.net/pictures/14/03/05/11/10/247578.jpg	2005	Accion, Crimen, Suspenso y Superheroes.	140	Bruce Wayne vive obsesionado con el recuerdo de la muerte de sus padres. Atormentado, se va de Gotham y encuentra a un extraño personaje que lo entrena en todas las disciplinas físicas y mentales que le servirán para combatir el Mal..	Christopher Nolan	Christian Bale, Michael Caine, Liam Neeson, Katie Holmes, Gary Oldman, Cillian Murphy, Tom Wilkinson,  Rutger Hauer, Ken Watanabe, Mark Boone Junior, Linus Roache, Morgan Freeman.	Warner Bros. Pictures	Estados Unidos	7.4	https://www.youtube.com/watch?v=BUt97Dv0y9E
4	Batman (1989)	https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQSZugiOKWGmokjtfdCBbxYjkQI4byR13BPrw&s	1989	Acción, Aventura y Superhéroes.	126	El caballero oscuro conocido como Batman defiende a la corrupta e insegura ciudad de Gotham de su enemigo principal, un payaso homicida conocido como Joker..	Tim Burton	Jack Nicholson, Michael Keaton, Kim Basinger, Robert Wuhl, Pat Hingle, Billy Dee Williams, Michael Gough y Jack Palance.	PolyGram Filmed Entertainment	Estados Unidos	6.8	https://www.youtube.com/watch?v=ygK7sAavO0c
5	Batman Returns 	https://m.media-amazon.com/images/M/MV5BOGZmYzVkMmItM2NiOS00MDI3LWI4ZWQtMTg0YWZkODRkMmViXkEyXkFqcGdeQXVyODY0NzcxNw@@._V1_.jpg	1992	Acción, Fantasía y Superhéroes.	126	Batman y la seductora Catwoman en la más oscura de sus aventuras, colaboran juntos para salvar la ciudad de Gotham, del Hombre Pingüino.	Tim Burton	Michael Keaton, Danny DeVito, Michelle Pfeiffer, Christopher Walken, Michael Gough, Pat Hingle, Michael Murphy y Vincent Schiavelli.	Warner Bros. Pictures	Estados Unidos	6.4	https://www.youtube.com/watch?v=YJ6tQBrsl-Y
6	Batman y Robin 	https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRRafpOkLKjHKzCCa62FNF4lP1c7_qhSrykNg&s	1997	Superhéroes, Ciencia ficción, Acción, Aventura y Comedia.	125	Batman y su compañero Robin deben enfrentarse a un nuevo villano, el Sr. Frío, que intentará congelar a todos los habitantes de Gotham.	Joel Schumacher	George Clooney, Arnold Schwarzenegger, Uma Thurman, Alicia Silverstone, Robert Swenson, Michael Gough, Pat Hingle, John Glover y Elle Macpherson.	Warner Bros. Pictures	Estados Unidos	3.6	https://www.youtube.com/watch?v=JEo0ICIKk9c
7	Batman Forever	https://m.media-amazon.com/images/M/MV5BNDdjYmFiYWEtYzBhZS00YTZkLWFlODgtY2I5MDE0NzZmMDljXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg	1995	Superhéroes, Ciencia ficción, Acción y Aventura.	121	La ciudad de Gotham está amenazada por dos hombres: Dos caras y un psicópata que ha inventado un aparato que permite absorber las ondas cerebrales de los seres humanos. Ambos se unirán para lograr sus propósitos.	Joel Schumacher	Val Kilmer, Tommy Lee Jones, Jim Carrey, Nicole Kidman, Michael Gough, Pat Hingle y Drew Barrymore.	Warner Bros. Pictures	Estados Unidos	4.6	https://www.youtube.com/watch?v=TkSgCsYAWY8
8	The Lego Batman Movie	https://m.media-amazon.com/images/M/MV5BMTcyNTEyOTY0M15BMl5BanBnXkFtZTgwOTAyNzU3MDI@._V1_.jpg	2017	Animación, Superhéroes y Comedia.	104	El irreverente Batman, que también tiene algo de artista frustrado, intentará salvar la ciudad una vez más. Se están produciendo cambios en Gotham, y Batman tiene que salvar la ciudad del Joker, un peligroso villano. Sin embargo, Batman no podrá hacerlo solo y deberá aprender a trabajar con sus demás aliados.	Chris McKay	Will Arnett, Zach Galifianakis, Michael Cera, Rosario Dawson y Ralph Fiennes.	Warner Bros. Pictures	Estados Unidos	6.4	https://www.youtube.com/watch?v=JHxhTOxX_bs
9	Batman: The Dark Knight	https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRGynrte4ZbbyvDGDQJltnfyoBqZE2fioii2g&s	2008	Acción, Crimen, Drama y Suspenso.	152	Con la ayuda del teniente Jim Gordon y del Fiscal del Distrito Harvey Dent, Batman mantiene a raya el crimen organizado en Gotham. Todo cambia cuando aparece el Joker, un nuevo criminal que desencadena el caos y tiene aterrados a los ciudadanos.	Christopher Nolan	Christian Bale, Michael Caine, Heath Ledger, Gary Oldman, Aaron Eckhart, Maggie Gyllenhaal y Morgan Freeman.	Warner Bros. Pictures	Estados Unidos	8.1	https://www.youtube.com/watch?v=EXeTwQWrcwY
2	The Batman	https://comicparatodos.wordpress.com/wp-content/uploads/2022/03/the-batman.jpg	2022	Accion, Crimen, Suspenso, y Superheroes.	176	En su segundo año luchando contra el crimen, Batman explora la corrupción existente en la ciudad de Gotham y el vínculo de esta con su propia familia. Además, entrará en conflicto con un asesino en serie conocido como "el Acertijo".	Matt Reeves	Robert Pattinson, Zoë Kravitz, Paul Dano, Jeffrey Wright, John Turturro, Colin Farrell, Andy Serkis.	DC Films	Estados Unidos	6.9	https://www.youtube.com/watch?v=YNl8yV8oPZM
3	Batman vs Superman: Dawn of Justice	https://www.lavanguardia.com/peliculas-series/images/movie/poster/2022/6/w1280/dQWpXwL2z4NdU86zn8Go3un8PmX.jpg	2016	Accion, Aventura, Ciencia ficción fantástica y Superheroes	151	Mientras el mundo debate qué tipo de héroe necesita, las hazañas de Superman tienen peligrosas consecuencias. En plena guerra entre el vigilante de Gotham y el defensor de Metrópolis, una nueva amenaza pone a la humanidad en grave peligro.	Zack Snyder	Ben Affleck, Henry Cavill, Amy Adams, Jesse Eisenberg, Diane Lane,  Laurence Fishburne, Jeremy Irons, Holly Hunter y Gal Gadot	Warner Bros. Pictures	Estados Unidos	5.5	https://www.youtube.com/watch?v=Vzi5Q5aIGJU
10	Batman: The Dark Knight Rises	https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-hOXOOf4X2JM84kxuaUSLOXJwVi3q7L5oCQ&s	2012	Acción, Crimen, Drama y Suspenso.	165	Hace ya ocho años desde que Batman se convirtió en fugitivo al asumir la muerte de Harvey. La dura Ley Dent sigue aplacando la criminalidad de Gotham, aunque la llegada de una gata ladrona y un misterioso terrorista enmascarado lo cambiará todo.	Christopher Nolan	Christian Bale, Michael Caine, Gary Oldman, Anne Hathaway, Tom Hardy, Marion Cotillard, Joseph Gordon-Levitt, Morgan Freeman y Liam Neeson	Warner Bros. Pictures	Estados Unidos	7.5	https://www.youtube.com/watch?v=c_BZOsbX3MI
11	John Wick	https://m.media-amazon.com/images/M/MV5BMTU2NjA1ODgzMF5BMl5BanBnXkFtZTgwMTM2MTI4MjE@._V1_.jpg	2014	Acción, Aventura y Suspenso.	101	La ciudad de Nueva York se llena de balas cuando John Wick, un exasesino a sueldo, regresa de su retiro para enfrentar a los mafiosos rusos, liderados por Viggo Tarasov, que destruyeron todo aquello que él amaba y pusieron precio a su cabeza.	Chad Stahelskia​	Keanu Reeves, Mikael Nyqvist, Alfie Allen, Adrianne Palicki, Bridget Moynahan, Dean Winters, Ian McShane, John Leguizamo y Willem Dafoe.	MJW Films	Estados Unidos	6.4	https://www.youtube.com/watch?v=C0BMx-qxsP4
12	John Wick: Chapter 2	https://m.media-amazon.com/images/M/MV5BMjE2NDkxNTY2M15BMl5BanBnXkFtZTgwMDc2NzE0MTI@._V1_.jpg	2017	Acción, Aventura y Suspenso.	122	El legendario asesino John Wick se ve obligado a salir de su retiro por culpa de un exsocio que intenta controlar un siniestro grupo internacional de asesinos. Obligado a ayudarle por un juramento de sangre, John viaja a Roma para enfrentarse a algunos de los asesinos más letales del mundo.	Chad Stahelskia​	Keanu Reeves, Laurence Fishburne, Riccardo Scamarcio, Ruby Rose, Lance Reddick, Peter Stormare, Bridget Moynahan, Franco Nero, John Leguizamo e Ian McShane.	Summit Entertainment	Estados Unidos	6.4	https://www.youtube.com/watch?v=XGk2EfbD_Ps
18	Star Wars: Episode I - The Phantom Menace	https://muvix.cl/CDN/media/entity/get/FilmPosterGraphic/A000000559?referenceScheme=Global&allowPlaceHolder=true	1999	Space opera, Blockbuster y Ciencia ficción.	136	Obi-Wan Kenobi es un joven aprendiz caballero Jedi bajo la tutela de Qui-Gon Jinn; Anakin Skywalker, quien después será padre de Luke Skywalker y se convertirá en Darth Vader, solamente es un niño de 9 años. Cuando la Federación de Comercio corta todas las rutas al planeta Naboo, Qui-Gon y Obi-Wan son asignados para solucionar el problema.	George Lucas	Liam Neeson, Ewan McGregor, Natalie Portman, Jake Lloyd, Pernilla August, Ray Park, Ahmed Best, Anthony Daniels, Kenny Baker,Hugh Quarshie, Ian McDiarmid, Silas Carson, Samuel L. Jackson y Frank Oz.	Lucasfilm	Estados Unidos	6.2	https://www.youtube.com/watch?v=n1CUHjrc9Sc
16	Top Gun: Maverick	https://es.web.img2.acsta.net/pictures/22/03/29/15/57/1533124.jpg	2022	Acción y Drama.	131	Maverick, quien lleva 30 años de servicio, es ahora instructor de pilotos militares. Una última misión, un sacrificio final, obliga a este maestro de los cielos a enfrentar las heridas abiertas del pasado y sus temores más profundos.	Joseph Kosinski	Tom Cruise, Val Kilmer, Miles Teller, Jennifer Connelly, Glen Powell, Lyliana Wray, Ed Harris, Monica Barbaro, Jon Hamm y Charles Parnell.	Paramount Pictures	Estados Unidos	7.0	https://www.youtube.com/watch?v=qSqVVswa420
15	Top gun	https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSuvQjD4NLvQppSAdjm2nASuGwHLAfxKYj75Q&s	1986	Acción y Drama.	110	El joven piloto Maverick Mitchell acude a una prestigiosa escuela aérea, famosa por formar a los mejores pilotos de combate del país. Maverick se siente atraído por su hermosa instructora, mientras desarrolla una intensa rivalidad con otro piloto.	Tony Scott	Tom Cruise, Kelly McGillis, Val Kilmer, Anthony Edwards y Tom Skerritt.	Paramount Pictures	Estados Unidos	6.0	https://www.youtube.com/watch?v=xa_z57UatDY
14	John Wick: Chapter 4	https://m.media-amazon.com/images/S/pv-target-images/6d3d1461d50778271845ce7ec81ba2c5d76a20f7f84e5061cd099aabaedc77f9.jpg	2023	Acción, Aventura y Suspenso.	169	El marqués Vincent de Gramont pretende matar a John Wick para afianzar su poder en la Orden Suprema. Sin embargo, John tratará de adelantarse a cada uno de sus movimientos hasta lograr enfrentarse cara a cara con su peor enemigo.	Chad Stahelskia​	Keanu Reeves, Laurence Fishburne, Ian McShane, Lance Reddick, Rina Sawayama, Donnie Yen, Shamier Anderson, Bill Skarsgård, Hiroyuki Sanada, Scott Adkins, Clancy Brown y Marko Zaror.	Thunder Road Pictures	Estados Unidos	6.7	https://www.youtube.com/watch?v=8ubRKDsM1FI
19	Star Wars: Episode II - Attack Of The Clones	https://es.web.img2.acsta.net/medias/nmedia/18/90/04/31/20078125.jpg	2002	Space opera, Blockbuster y Ciencia ficción.	142	En el Senado Galáctico reina la inquietud. Varios miles de sistemas solares han declarado su intención de abandonar la República. Este movimiento separatista, liderado por el misterioso conde Dooku, ha provocado que al limitado número de caballeros Jedi les resulte difícil mantener la paz y el orden en la galaxia. La senadora Amidala, antigua Reina de Naboo, regresa al Senado Galáctico para dar su voto en la crítica cuestión de crear un ejército de la República que ayude a los desbordados Jedi.	George Lucas	Ewan McGregor, Hayden Christensen, Natalie Portman, Frank Oz, Ian McDiarmid, Pernilla August, Ahmed Best, Oliver Ford Davies, Temuera Morrison, Anthony Daniels, Silas Carson, Kenny Baker, Samuel L. Jackson y Christopher Lee.	Lucasfilm	Estados Unidos	6.3	https://www.youtube.com/watch?v=gYbW1F_c9eM
17	El secreto de sus ojos	https://pics.filmaffinity.com/El_secreto_de_sus_ojos-650081510-large.jpg	2009	Suspenso y Drama.	127	Benjamín Espósito es un oficial de un Juzgado de Instrucción de Buenos Aires que acaba de jubilarse. Su sueño es escribir una novela y, para ello, intentará dar solución a un caso abierto desde hace varias décadas, del cual fue testigo y protagonista. Reviviendo el caso, vuelve también a su memoria el recuerdo de una mujer, a quien ha amado en silencio durante todos esos años.	Juan José Campanella	Ricardo Darín, Soledad Villamil, Pablo Rago, Javier Godino y Guillermo Francella.	Haddock Films	Argentina	8.1	https://www.youtube.com/watch?v=hKa8U-8vsfU
20	Star Wars: Episode III - Revange Of The Sinth	https://m.media-amazon.com/images/S/pv-target-images/3a991f1ad651779c8701339593c0a7c6afa18ba8844da38a1740e9fea2ebe873.jpg	2005	Accion, Aventura, Space opera, Blockbuster y Ciencia ficción.	139	La República se desmorona bajo los ataques del despiadado Lord Sith, el conde Dooku. Hay héroes en ambos bandos, pero el mal está por doquier. En una contundente jugada, el diabólico líder droide, el general Grievous, ha irrumpido en la capital de la República y ha secuestrado al Canciller Palpatine, líder del senado Galáctico. Mientras el ejército droide separatista trata de huir con su valioso rehén, Obi Wan y Anakin inician una misión desesperada para liberar al Canciller cautivo.	George Lucas	Ewan McGregor, Hayden Christensen, Natalie Portman, Ian McDiarmid, Samuel L. Jackson, Christopher Lee, Anthony Daniels, James Earl Jones, Kenny Baker y Frank Oz.	Lucasfilm	Estados Unidos	7.1	https://www.youtube.com/watch?v=5UnjrG_N8hU
23	Star Wars: Episode VI - Return Of The Jedi	https://www.hobbyconsolas.com/sites/navi.axelspringer.es/public/media/image/2016/11/guerra-galaxias-episodio-vi-retorno-jedi_0.jpg	1983	Accion, Aventura, Space opera, Blockbuster y Ciencia ficción.	128	Seis meses después de que Han Solo fuera capturado y congelado en carbonita en la Ciudad de las Nubes, el Imperio Galáctico está construyendo una nueva Estrella de la Muerte. Mientras tanto, el joven Luke lucha para alcanzar la maestría jedi.	George Lucas	Mark Hamill, James Earl Jones, David Prowse, Sebastian Shaw, Harrison Ford, Carrie Fisher, Billy Dee Williams, Anthony Daniels, Kenny Baker, Peter Mayhew, Ian McDiarmid, Frank Oz y Alec Guinness.	Lucasfilm	Estados Unidos	7.9	https://www.youtube.com/watch?v=p4vIFhk621Q
26	Star Wars: Episode IX - The Last Jedi	https://www.animeworld.com.ar/mods/html/fil/Model/Product/3299/estrenos_marzo_2020_-_semana_2_-_star_wars_episodio_9_copy.jpg.webp	2019	Accion, Aventura, Space opera, Blockbuster y Ciencia ficción.	142	La Resistencia sobreviviente se enfrenta a la Primera Orden, y Rey, Finn, Poe y el resto de los héroes encararán nuevos retos y una batalla final con la sabiduría de las generaciones anteriores.	J.J. Abrams	Carrie Fisher, Mark Hamill, Adam Driver, Daisy Ridley, John Boyega, Oscar Isaac, Anthony Daniels, Naomi Ackie, Domhnall Gleeson, Richard E. Grant, Keri Russell, Joonas Suotamo, Kelly Marie Tran, Ian McDiarmid y Billy Dee Williams.	Lucasfilm	Estados Unidos	5.6	https://www.youtube.com/watch?v=8Qn_spdM5Zg
24	Star Wars: Episode VII - The Force Awakens	https://image.tmdb.org/t/p/original/wG3nQWTclxQqmr3i3dReSbB6bOF.jpg	2015	Accion, Aventura, Space opera, Blockbuster y Ciencia ficción.	136	Treinta años después de la victoria de la Alianza Rebelde sobre la segunda Estrella de la Muerte, la galaxia tiene que enfrentarse a una nueva amenaza: el malvado Kylo Ren y la Primera Orden. Cuando el desertor Finn llega a un planeta desierto conoce a Rey, cuyo androide contiene un mapa secreto. Juntos, la joven pareja unirá fuerzas con Han Solo para asegurarse de que la resistencia encuentra a Luke Skywalker, el último de los caballeros Jedi.	J. J. Abrams	Mark Hamill, James Earl Jones, David Prowse, Sebastian Shaw, Harrison Ford, Carrie Fisher, Billy Dee Williams, Anthony Daniels, Kenny Baker, Peter Mayhew, Ian McDiarmid, Frank Oz y Alec Guinness.	Lucasfilm	Estados Unidos	6.7	https://www.youtube.com/watch?v=sGbxmsDFVnE
68	Matrix: Resurrecciones	https://play-lh.googleusercontent.com/H6Ioa-dJbdily7_7kbL6ZLPaZXpm8T5fOfTAwZYa7UXjtR30ekNWD2ZHl2HwI_WcT0E-D7ZZ4uxcJfuvwTDw	2021	Accion y Ciencia ficción.	147	Thomas Anderson lleva una vida cómoda como una eminencia dentro del mundo de los videojuegos, pero tiene problemas para discernir entre lo que es realidad y lo que no lo es. Thomas deberá decidir si sigue al conejo blanco una vez más.	Lana Wachowski	Keanu Reeves, Carrie-Anne Moss, Jada Pinkett Smith, Lambert Wilson, Priyanka Chopra, Daniel Bernhardt, Neil Patrick Harris, Jonathan Groff, Christina Ricci, Jessica Henwick, Eréndira Ibarra y Yahya Abdul-Mateen II.	Warner Bros. Pictures	Estados Unidos	4.9	https://www.youtube.com/watch?v=Rw5JzpvJTfM
67	Matrix Revoluciones	https://es.web.img2.acsta.net/medias/nmedia/18/78/91/51/20076377.jpg	2003	Accion y Ciencia ficción.	129	Neo sigue adquiriendo nuevos poderes. Ahora, algo más cansado, ha llegado a la tierra de nadie, un tranquilo lugar entre Matrix y el mundo de las máquinas. Trinity vela el cuerpo en coma de Neo, mientras Morfeo se enfrenta a una revelación.	Hermanas Wachowski	Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss, Hugo Weaving, Monica Bellucci y Jada Pinkett Smith.	Warner Bros. Pictures	Estados Unidos y Australia	6.0	https://www.youtube.com/watch?v=hMbexEPAOQI
69	Máxima velocidad	https://mx.web.img3.acsta.net/pictures/18/10/01/06/08/2542886.jpg	1994	Accion.	116	Jack Traven, interpretado por Keanu Reeves, es un policía de Los Ángeles que se enfrenta a uno de los mayores retos de su carrera: tratar de dar caza a un peligroso terrorista llamado Howard Payne (Hopper), el cual ha puesto una bomba en un autobús de la ciudad que explotará si disminuye su velocidad por debajo de las 50 millas por hora.	Jan de Bont	Keanu Reeves, Sandra Bullock, Dennis Hopper, Joe Morton y Jeff Daniels.	20th Century Fox	Estados Unidos	5.9	https://www.youtube.com/watch?v=icKnWa_Thlk
21	Star Wars: Episode IV - A New Hope	https://assets.scriptslug.com/live/img/posters/star-wars-episode-iv-a-new-hope-1977.jpg?utime=20240519142212	1977	Accion, Aventura, Space opera, Blockbuster y Ciencia ficción.	121	La nave en la que viaja la princesa Leia es capturada por las tropas imperiales al mando del temible Darth Vader. Antes de ser atrapada, Leia consigue introducir un mensaje en su robot R2-D2, quien acompañado de su inseparable C-3PO logran escapar. Tras aterrizar en el planeta Tattooine son capturados y vendidos al joven Luke Skywalker, quien descubrirá el mensaje oculto que va destinado a Obi Wan Kenobi, maestro Jedi a quien Luke debe encontrar para salvar a la princesa.	George Lucas	Mark Hamill, Harrison Ford, Carrie Fisher, Peter Cushing, Alec Guinness, Anthony Daniels, Kenny Baker, Peter Mayhew, David Prowse, Jack Purvis, Eddie Byrne y James Earl Jones.	Lucasfilm	Estados Unidos	7.9	https://www.youtube.com/watch?v=vZ734NWnAHA
31	Terminator 1	https://es.web.img3.acsta.net/pictures/16/02/12/15/14/218373.jpg	1984	Ciencia ficcion y Acción.	108	En el año 2029 las máquinas dominan el mundo. Los rebeldes que luchan contra ellas tienen como líder a John Connor, un hombre que nació en los años ochenta. Para eliminarlo y así acabar con la rebelión, las máquinas envían al pasado el robot Terminator con la misión de matar a Sarah Connor, la madre de John, e impedir así su nacimiento. Sin embargo, un hombre del futuro intentará protegerla.	James Cameron	Arnold Schwarzenegger, Linda Hamilton y Michael Biehn.	Hemdale Film Corporation	Estados Unidos	7.1	https://www.youtube.com/watch?v=k64P4l2Wmeg&t=39s
27	Kung Fu Panda	https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQCvhtLQ80OqelAWJn4PsbFao1MQyh2B3EOeg&s	2008	Animación, Aventura, Comedia y Acción.	92	El panda Po trabaja en la tienda de fideos de su familia y que sueña en convertirse en un maestro del kung-fu, se hace una realidad cuando es inesperadamente elegido para cumplir una antigua profecía y debe estudiar artes marciales con sus ídolos, los Cinco Furiosos. Po necesitará toda la sabiduría, fortaleza y habilidades para poder proteger a su gente de Tai Lung, un leopardo de nieve.	Mark Osborne	Jack Black, Jackie Chan, Dustin Hoffman, Angelina Jolie, Seth Rogen, Ian McShane, Lucy Liu y David Cross.	DreamWorks Animation	Estados Unidos	6.5	https://www.youtube.com/watch?v=NRc-ze7Wrxw
32	Terminator 2: Judgment Day 	https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSJliUrAgkzbhnBCs5flMdshgTd80WpLmjpGw&s	1991	Ciencia ficcion y Acción.	137	Algunos años antes, un viajero del tiempo le reveló a la madre de John que su hijo sería el salvador de la humanidad. Cuando un nuevo androide mejorado llega del futuro para asesinar a John, un viejo modelo será enviado para protegerle.	James Cameron	Arnold Schwarzenegger, Linda Hamilton, Edward Furlong y Robert Patrick.	Carolco Pictures	Estados Unidos	7.5	https://www.youtube.com/watch?v=CRRlbK5w8AE
33	Terminator 3: Rise Of The Machines 	https://m.media-amazon.com/images/M/MV5BMTk5NzM1ODgyN15BMl5BanBnXkFtZTcwMzA5MjAzMw@@._V1_.jpg	2003	Ciencia ficcion y Acción.	109	Un robot de un futuro postapocalíptico viaja en el tiempo con la misión de proteger a John Connor y a su futura esposa de un modelo cibernético más sofisticado que ha sido enviado para matarlo y asegurar el triunfo de las máquinas sobre los humanos.	Jonathan Mostow.	Arnold Schwarzenegger, Nick Stahl, Claire Danes, Kristanna Loken y David Andrews.	C2 Pictures	Estados Unidos	5.2	https://www.youtube.com/watch?v=5UgPJhyJmlM
34	Terminator Salvation 	https://m.media-amazon.com/images/M/MV5BODBlOTJhZjItMGRmYS00YzM1LWFmZTktOTJmNDMyZTBjMjBkXkEyXkFqcGdeQXVyMjMwNDgzNjc@._V1_FMjpg_UX1000_.jpg	2009	Ciencia ficcion y Acción.	118	Mientras las máquinas se preparan para un ataque final, John Connor y un extraño entran en el corazón de Skynet y descubren que va a haber una terrible masacre.	Joseph McGinty Nichol.	Christian Bale, Sam Worthington, Anton Yelchin, Bryce Dallas Howard, Moon Bloodgood, Common, Helena Bonham Carter y Michael Ironside.	The Halcyon Company	Estados Unidos	5.9	https://www.youtube.com/watch?v=-Czz-TcWCkA
29	Kung Fu Panda 3	https://m.media-amazon.com/images/M/MV5BMTUyNzgxNjg2M15BMl5BanBnXkFtZTgwMTY1NDI1NjE@._V1_FMjpg_UX1000_.jpg	2016	Animación, Aventura, Comedia y Acción.	95	El malvado Kai, confinado en el reino de los espíritus desde hace 500 años, consigue arrebatarle el chi al maestro Oogway, lo que le permite regresar al mundo de los mortales. Po deberá hacer frente a dos desafíos épicos: uno, de origen sobrenatural; el otro, muy cerca de su hogar, con la aparición del que dice ser su padre biológico.	Jennifer Yuh Nelson	Jack Black, Bryan Cranston, James Hong, Dustin Hoffman, Angelina Jolie, J. K. Simmons, Seth Rogen, Lucy Liu, David Cross, Kate Hudson, Randall Duk Kim, Wayne Knight y Jackie Chan.	DreamWorks Animation	Estados Unidos	6.0	https://www.youtube.com/watch?v=xADC5FrVeTs
28	Kung Fu Panda 2	https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRZ0yMKXSKU1oqd6qEdbyfjyzmTS_5ZqsElNw&s	2011	Animación, Aventura, Comedia y Acción.	90	Ahora conocido como el Dragón Guerrero, Po protege el Valle de la Paz junto con sus amigos y compañeros maestros de kung fu, los Cinco Furiosos. Sin embargo, un peligroso villano amenaza la nueva e impresionante vida de Po con planes para usar un arma secreta para desaparecer el arte marcial y conquistar China. Con el fin de derrotar a su nuevo enemigo, Po tiene que recordar su pasado y desbloquear secretos de sus misteriosos orígenes.	Jennifer Yuh Nelson	Jack Black, Jackie Chan, Dustin Hoffman, Angelina Jolie, Seth Rogen, Ian McShane, Lucy Liu, David Cross, James Hong, Gary Oldman, Michelle Yeoh, Jean-Claude Van Damme y Victor Garber.	DreamWorks Animation	Estados Unidos	6.2	https://www.youtube.com/watch?v=FQ63rqSRrEI
35	Terminator Genesis 	https://im.ziffdavisinternational.com/ign_es/screenshot/default/terminatorintlposter1_7s3r.jpg	2015	Ciencia ficcion y Acción.	126	En Los Ángeles del año 2032, John Connor, líder de la resistencia humana contra las máquinas que se han apoderado de la Tierra, prepara la ofensiva definitiva contra Skynet. Junto a él lucha su mano derecha, el sargento Kyle Reese. Connor envía a Reese a 1984 para salvar a su madre, Sarah, de un Terminator.	Alan Taylor.	Arnold Schwarzenegger, Jai Courtney, Emilia Clarke y Jason Clarke.	Skydance Productions.	Estados Unidos	5.2	https://www.youtube.com/watch?v=0vrj9V-vYZc
70	La lista de Schindler	https://pics.filmaffinity.com/La_lista_de_Schindler-473662617-large.jpg	1993	Cine bélico, cine biográfico y drama	195	El empresario alemán Oskar Schindler, miembro del Partido Nazi, pone en marcha un elaborado, costoso y arriesgado plan para salvar a más de mil judíos del Holocausto.	Steven Spielberg	Liam Neeson, Ralph Fiennes, Ben Kingsley, Caroline Goodall, Embeth Davidtz y Jonathan Sagall.	Universal Pictures	Estados Unidos	8.7	https://www.youtube.com/watch?v=BmkchuRJ82w
30	Kung Fu Panda 4	https://es.web.img3.acsta.net/pictures/23/12/20/17/49/3528056.jpg	2024	Animación, Aventura, Comedia y Acción.	94	Po está entrenando a un nuevo guerrero que ocupe su lugar para que él pueda convertirse en líder espiritual del Valle de la Paz. Sin embargo, la irrupción de una malvada hechicera que puede cambiar de apariencia trastoca sus planes.	Mike Mitchell	Jack Black, Viola Davis, Dustin Hoffman, James Hong, Bryan Cranston, Ian McShane, Ke Huy Quan, Angelina Jolie y Seth Rogen.	DreamWorks Animation	Estados Unidos	5.7	https://www.youtube.com/watch?v=tYMDHo9xy1I
36	Terminator: Dark Fate 	https://es.web.img3.acsta.net/pictures/19/09/03/16/58/5053583.jpg	2019	Ciencia ficcion y Acción.	128	En Ciudad de México, un nuevo Terminator modificado, también conocido como Rev-9, llega del futuro para matar a una joven trabajadora de una fábrica llamada Dani Ramos. La cyborg híbrida Grace también es enviada al pasado para proteger a Ramos del aparentemente indestructible Rev-9. Las dos mujeres pronto recibirán ayuda de un par de aliados inesperados: la experimentada luchadora de la resistencia Sarah Connor y el T-800.	Tim Miller.	Linda Hamilton, Arnold Schwarzenegger, Mackenzie Davis, Natalia Reyes y Gabriel Luna.	Paramount Pictures.	Estados Unidos	5.2	https://www.youtube.com/watch?v=2LKDwZlggNI
38	El Señor de los Anillos: Las Dos Torres	https://es.web.img3.acsta.net/medias/nmedia/18/89/85/69/20070008.jpg	2002	Aventura y Fantasía épica.	172	Los hobbits Frodo y Sam descubren que Gollum les está siguiendo. La criatura les promete guiarlos hasta las puertas de Mordor si después lo dejan libre. Aragorn, el elfo Legolas y Gimli el enano llegan al reino de Rohan y descubren que el rey Theoden está bajo el conjuro de Sarumán. El traidor quiere el control del reino para continuar con sus planes en Mordor, a la espera de la guerra en la Tierra Media.	Peter Jackson.	Elijah Wood, Ian McKellen, Liv Tyler, Viggo Mortensen, Sean Astin, Billy Boyd, Dominic Monaghan, John Rhys-Davies, Christopher Lee, Orlando Bloom, Karl Urban, Bernard Hill, Miranda Otto y Andy Serkis.	New Line Cinema.	Estados Unidos y Nueva Zelanda	8.0	https://www.youtube.com/watch?v=Qmwq4viqxXQ
39	El Señor de los Anillos: El Retorno Del Rey	https://es.web.img2.acsta.net/medias/nmedia/18/89/68/19/20061877.jpg	2003	Aventura y Fantasía épica.	201	La batalla por la Tierra Media ha empezado. Las fuerzas de Saruman han sido destruidas y por primera vez parece que hay una pequeña esperanza. Sin embargo, el poder de Sauron crece y su interés se centra en Gondor, el último reducto de los hombres, cuyo heredero es Aragorn. Mientras, Frodo y Sam, guiados por Gollum, siguen su peligrosa misión a través de Mordor para destruir el anillo.	Peter Jackson.	Elijah Wood, Ian McKellen, Liv Tyler, Viggo Mortensen, Sean Astin, Billy Boyd, Dominic Monaghan, Orlando Bloom, John Rhys-Davies, John Noble, David Wenham, Bernard Hill , Miranda Otto, Karl Urban y Andy Serkis.	New Line Cinema.	Estados Unidos y Nueva Zelanda	8.2	https://www.youtube.com/watch?v=mZYms2vsm2Y
40	Volver al Futuro	https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSARwCFB6M36a-YEdVSHKjbJjAiic23UyYlvA&s	1985	Ciencia Ficcion,Comedia y Aventura.	117	El adolescente Marty McFly es amigo de Doc, un científico que ha construido una máquina del tiempo. Cuando los dos prueban el artefacto, un error fortuito hace que Marty llegue a 1955, año en el que sus padres iban al instituto y todavía no se habían conocido. Después de impedir su primer encuentro, Marty deberá conseguir que se conozcan y se enamoren, de lo contrario su existencia no sería posible.	Robert Zemeckis.	Michael J. Fox, Christopher Lloyd, Lea Thompson, Crispin Glover, Thomas F. Wilson y Marc McClure.	Universal Pictures.	Estados Unidos	7.5	https://www.youtube.com/watch?v=8x0s7U0DBWI
41	Volver al futuro II	https://es.web.img3.acsta.net/pictures/14/04/03/13/45/034916.jpg	1989	Ciencia Ficcion,Comedia y Aventura.	109	Doc vuelve a aparecer con una máquina del tiempo mucho más modernizada y le pide a Marty y a su novia que le acompañen al futuro. En el Hill Valley de 2015 deberán solucionar un problema con la ley que tendrá uno de los futuros hijos de Marty y Jenny. En el futuro, Biff Tannen roba la máquina del tiempo y vuelve al pasado para darle a su hijo un libro con estadísticas deportivas para poder ganar una enorme fortuna en las apuestas. Marty y Doc tendrán que parar la posible catástrofe del destino.	Robert Zemeckis.	Michael J. Fox, Christopher Lloyd, Lea Thompson, Crispin Glover, Thomas F. Wilson y Marc McClure.	Amblin Entertainment.	Estados Unidos	7.2	https://www.youtube.com/watch?v=ixLXR27eGCw&t=1s
42	Volver al futuro III	https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTtuVvd8yahD-VoRYT__hJhCZd9LhPto0rHmA&s	1990	Ciencia Ficcion,Comedia, Western y Aventura	119	Marty McFly sigue en 1955 y Doc ha retrocedido al año 1885, la época del salvaje oeste. Marty recibe una carta de Doc en la que le informa de que la máquina del tiempo está averiada y no puede volver al presente, pero que no le importa seguir en el pasado. Sin embargo, Marty descubre una tumba en la que lee que Doc murió en 1885 y decide ir a rescatar a su amigo.	Robert Zemeckis.	Michael J. Fox, Christopher Lloyd, Mary Steenburgen, Thomas F. Wilson y Lea Thompson.	Universal Pictures	Estados Unidos	6.6	https://www.youtube.com/watch?v=WmBX7CA-AAc
45	Alien 3	https://es.web.img3.acsta.net/c_310_420/medias/nmedia/18/78/65/71/20076549.jpg	1992	Ciencia Ficcion, Accion y Terror	114	Ripley libera a un grupo de convictos desarmados en un desesperado intento de matar al extraterrestre que los persigue.	David Fincher.	Sigourney Weaver, Lance Henriksen, Charles S. Dutton, Charles Dance, Paul McGann, Pete Postlethwaite.	20th Century Fox.	Estados Unidos	5.9	https://www.youtube.com/watch?v=O57vJ59Eq5Q
44	Alien 2: El regreso	https://4.bp.blogspot.com/-kCfTovg5GgU/TgpZT89_XRI/AAAAAAAAA8w/ToJL1pxIBgo/s1600/Alien+2.jpg	1986	Ciencia Ficcion, Accion y Terror	137	La sobreviviente de un ataque extraterrestre regresa al planeta LV-426 acompañada por unos marines. Juntos, deberán destruir a un monstruo.	James Cameron.	Sigourney Weaver, Michael Biehn, Lance Henriksen, Carrie Henn, Bill Paxton, Paul Reiser.	20th Century Fox.	Estados Unidos	7.4	https://www.youtube.com/watch?v=LRQJEcmo4-8
53	Los juegos del hambre: Balada de pájaros cantores y serpientes	https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcReneMC1Wf0RWECUX6uFCeywk0ebqFTI0RTiw&s	2023	Acción, Drama y Aventura	158	Muchos años antes de convertirse en Presidente de Panem, el joven Coriolanus Snow es elegido mentor del Distrito 12 en los nuevos Juegos del Hambre. Aquí utiliza su encanto, astucia e inventiva para ayudar a su candidata a ganar.	Francis Lawrence	Tom Blyth, Rachel Zegler, Josh Andrés Rivera, Hunter Schafer, Jason Schwartzman, Burn Gorman, Peter Dinklage, Viola Davis	Warner Bros Pictures.	Estados Unidos	5.8	https://www.youtube.com/watch?v=IWjAy4lIyoY
49	Los juegos del hambre	https://es.web.img3.acsta.net/pictures/14/09/12/10/51/011753.jpg	2012	Ciencia ficción, Acción, Drama y Distopía	142	Para demostrar su poder, el régimen del estado totalitario de Panem organiza cada año "Los juegos del hambre". En ellos, 24 jóvenes compiten el uno contra el otro en una batalla en la que solo puede haber un superviviente. La joven Katniss se ofrece voluntaria para participar en los juegos para salvar a su hermana. Junto a ella participará Peeta, un joven al que ha conocido desde la infancia y que está enamorado de ella. Sin embargo, el Capitolio quiere convertirlos en contrincantes.	Gary Ross	Jennifer Lawrence, Josh Hutcherson, Liam Hemsworth, Woody Harrelson, Elizabeth Banks, Lenny Kravitz, Stanley Tucci, Donald Sutherland, Alexander Ludwig, Isabelle Fuhrman, Amandla Stenberg	Warner Bros Pictures.	Estados Unidos	6.2	https://www.youtube.com/watch?v=_8Ktfs2mBDY
50	Los juegos del hambre: En llamas	https://es.web.img2.acsta.net/pictures/210/455/21045552_20131001101323189.jpg	2013	Ciencia ficción, Acción, Drama y Distopía	146	Katniss Everdeen volvió a casa a salvo después de ganar la 74 edición de los Juegos del Hambre con su compañero Peeta. Sin embargo, ahora el Capitolio les obliga a abandonar de nuevo a su familia y amigos para participar en el Tour de la Victoria por todos los distritos. Mientras, el presidente Snow está preparando una nueva edición de los Juegos, que transformarán Panem para siempre.	Francis Lawrence	Jennifer Lawrence, Josh Hutcherson, Liam Hemsworth, Woody Harrelson, Elizabeth Banks, Lenny Kravitz, Philip Seymour Hoffman, Jeffrey Wright, Stanley Tucci, Sam Claflin, Jena Malone, Donald Sutherland	Warner Bros Pictures.	Estados Unidos	6.4	https://www.youtube.com/watch?v=wTwabD43r2w
51	Los juegos del hambre: Sinsajo- Parte 1	https://es.web.img3.acsta.net/pictures/14/09/12/10/51/011753.jpg	2014	Ciencia ficción, Acción, Drama y Distopía	146	Katniss Everdeen se encuentra en el Distrito 13 después de destrozar los juegos para siempre. Bajo el liderazgo de la comandante Coin y el consejo de sus amigos más leales, Katniss extiende sus alas mientras lucha por salvar a Peeta Mellark y a una nación alentada por su valentía.	Francis Lawrence	Sam Claflin, Jennifer Lawrence, Josh Hutcherson, Liam Hemsworth, Woody Harrelson, Elizabeth Banks, Julianne Moore, Jena Malone, Philip Seymour Hoffman, Stanley Tucci, Donald Sutherland	Warner Bros Pictures.	Estados Unidos	5.6	https://www.youtube.com/watch?v=3AuMlTD46tg
52	Los juegos del hambre: Sinsajo- Parte 2	https://es.web.img2.acsta.net/pictures/15/10/05/09/45/058912.jpg	2015	Ciencia ficción, Acción, Drama y Distopía	137	Finalmente el Distrito 13 consigue rescatar de las garras del Capitolio a Peeta Mellark. Las torturas psicológicas han hecho mella en el joven y está convencido de que Katniss es una peligrosa muto con la que hay que acabar. Junto con un grupo de amigos, Peeta y Katniss emprenden una arriesgada misión para liberar Panem. La joven heroína se dará cuenta de que no sólo está en juego su supervivencia, sino que también el futuro de todos.	Francis Lawrence	Jennifer Lawrence, Josh Hutcherson, Liam Hemsworth, Woody Harrelson, Elizabeth Banks, Julianne Moore, Philip Seymour Hoffman, Jeffrey Wright, Stanley Tucci, Donald Sutherland, Sam Claflin	Warner Bros Pictures.	Estados Unidos	5.6	https://www.youtube.com/watch?v=3-ar77u-Mww
46	Alien: Resurrección	https://musicart.xboxlive.com/7/8fb00800-0000-0000-0000-000000000002/504/image.jpg?w=1920&h=1080	1992	Ciencia Ficcion y Terror	109	Doscientos años después del sacrificio de Ripley para destruir al alien que quedaba en la galaxia, la teniente vuelve a la vida gracias a la clonación.	Jean-Pierre Jeunet.	Sigourney Weaver, Winona Ryder, Dominique Pinon, Ron Perlman, Gary Dourdan, Michael Wincott, Kim Flowers, Dan Hedaya, J.E. Freeman, Brad Dourif, Raymond Cruz, Leland Orser, Carolyn Campbell, Marlene Bush, David St. James	20th Century Fox.	Estados Unidos	5.6	https://www.youtube.com/watch?v=zu4WMF1yugo
47	Alien: Prometheus	https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRshf-IJduGlIbItIQmy0Gfs0PVK9wY20W0xA&s	2012	Ciencia Ficcion y Terror	124	La acción comienza en un planeta sin vida humana aparente. Al borde de una cascada, un extraterrestre humanoide espera mientras una enorme nave espacial, que permanecía inmóvil, empieza a alejarse. El humanoide bebe un líquido negro burbujeante y empieza a desintegrarse. Cuando sus restos corporales caen por la cascada, el ADN del extraterrestre sufre una reacción biogenética.	Ridley Scott.	Noomi Rapace, Michael Fassbender, Charlize Theron, Idris Elba, Guy Pearce, Logan Marshall-Green	20th Century Fox.	Estados Unidos	5.8	https://www.youtube.com/watch?v=aUwNASUI4y8
43	Alien 1: El octavo pasajero	https://images.justwatch.com/poster/9890794/s718/alien-el-octavo-pasajero.jpg	1979	Ciencia Ficcion y Terror	116	La tripulación del remolcador espacial Nostromo atiende una señal de socorro y, sin saberlo, sube a bordo una letal forma de vida extraterrestre.	Robert Zemeckis.	Tom Skerritt, Sigourney Weaver, Veronica Cartwright, Harry Dean Stanton, John Hurt, Ian Holm, Yaphet Kotto, Bolaji Badejo.	20th Century Fox.	Estados Unidos	8.1	https://www.youtube.com/watch?v=6q0I-OqZP14
48	Alien Covenant 	https://play-lh.googleusercontent.com/Cy39VIudZjv00OUTR1Nt6h_68aLU6g8xAdWEDDEuMJt6QmP9ihpFVqSsXNZxEDamwnmx	2017	Ciencia Ficcion y Terror	122	Durante un viaje interplanetario, la tripulación de la nave Covenant descubre un mundo nuevo y piensan que se trata de un lugar paradisíaco. Cuando llegan, se dan cuenta de que es un territorio aterrador, repleto de criaturas brutales. Mientras lo exploran se percatan de que no son los primeros en aterrizar en ese planeta.	Ridley Scott.	Michael Fassbender, Katherine Waterston, Billy Crudup, Danny McBride, Guy Pearce	20th Century Fox.	Estados Unidos	5.6	https://www.youtube.com/watch?v=_O6YW4Rxubk
13	John Wick: Chapter 3 Parabellum	https://musicart.xboxlive.com/7/261e5100-0000-0000-0000-000000000002/504/image.jpg?w=1920&h=1080	2019	Acción, Aventura y Suspenso.	131	John Wick regresa de nuevo pero con una recompensa sobre su cabeza que persigue unos mercenarios. Tras asesinar a uno de los miembros de su gremio, Wick es expulsado y se convierte en el foco de atención de todos los sicarios de la organización.	Chad Stahelskia​	Keanu Reeves, Halle Berry, Laurence Fishburne, Mark Dacascos, Asia Kate Dillon, Lance Reddick, Anjelica Huston e Ian McShane.	Summit Entertainment	Estados Unidos	6.4	https://www.youtube.com/watch?v=pU8-7BX9uxs
25	Star Wars: Episode VIII - The Last Jedi	https://hips.hearstapps.com/hmg-prod/images/los-ultimos-jedi-1575448992.jpg?crop=1xw:1xh;center,top&resize=980:*	2017	Accion, Aventura, Space opera, Blockbuster y Ciencia ficción.	152	La Primera Orden ha acorralado a los últimos miembros de la resistencia. Su última esperanza es que Finn se introduzca en la nave de Snoke y desactive el radar que les permite localizarlos. Mientras él trata, en compañía de una soldado de la Resistencia, de cumplir esta misión imposible, Rey se encuentra lejos, intentando convencer a Luke Skywalker de que la entrene y la convierta en la última jedi.	Rian Johnson	Mark Hamill, Carrie Fisher, Adam Driver, Daisy Ridley, John Boyega, Oscar Isaac, Andy Serkis, Domhnall Gleeson, Anthony Daniels, Gwendoline Christie, Kelly Marie Tran, Laura Dern, Frank Oz, Benicio Del Toro y Jimmy Vee.	Lucasfilm	Estados Unidos	6.1	https://www.youtube.com/watch?v=Q0CbN8sfihY
37	El Señor de los Anillos: La Comunidad del Anillo	https://es.web.img3.acsta.net/medias/nmedia/18/89/67/45/20061512.jpg	2001	Aventura y Fantasía épica.	178	En la Tierra Media, el Señor Oscuro Sauron forjó los Grandes Anillos del Poder y creó uno con el poder de esclavizar a toda la Tierra Media. Frodo Bolsón es un hobbit al que su tío Bilbo hace portador del poderoso Anillo Único con la misión de destruirlo. Acompañado de sus amigos, Frodo emprende un viaje hacia Mordor, el único lugar donde el anillo puede ser destruido. Sin embargo, Sauron ordena la persecución del grupo para recuperar el anillo y acabar con la Tierra Media.	Peter Jackson.	Elijah Wood, Ian McKellen, Liv Tyler, Viggo Mortensen, Sean Astin, Cate Blanchett, John Rhys-Davies, Billy Boyd, Dominic Monaghan, Orlando Bloom, Christopher Lee, Hugo Weaving, Sean Bean, Ian Holm, Andy Serkis, Marton Csokas y Craig Parker.	New Line Cinema.	Estados Unidos y Nueva Zelanda	8.0	https://www.youtube.com/watch?v=3GJp6p_mgPo
54	El niño con el pijama a rayas	https://es.web.img3.acsta.net/medias/nmedia/18/67/06/38/20350558.jpg	2008	Drama y Cine belico	94	Durante la Segunda Guerra Mundial, el pequeño hijo de un comandante de un campo de concentración desarrolla una amistad prohibida con un niño judío de 8 años.	Mark Herman	Vera Farmiga, David Thewlis, Rupert Friend, Asa Butterfield y Jack Scanlon	Miramax Films	Reino unido	6.9	https://www.youtube.com/watch?v=dRUe8JR8iWY
55	E.T., el extraterrestre	https://pics.filmaffinity.com/E_T_el_extraterrestre-391240254-large.jpg	1982	Ciencia ficcion.	114	Un pequeño extraterrestre de otro planeta queda abandonado en la Tierra cuando su nave se olvida de él. Está completamente solo y asustado hasta que Elliott, un niño de nueve años, lo encuentra y decide esconderlo en su casa para protegerlo. El chico y sus hermanos intentarán encontrar la forma de devolver al extraterrestre a su planeta antes de que lo encuentren los científicos y la policía.	Steven Spielberg	Henry Thomas, Robert MacNaughton, Drew Barrymore, Dee Wallace, Peter Coyote, K. C. Martel, Sean Frye, C. Thomas Howell, Erika Eleniak, Pat Welsh	Universal Pictures	Estados Unidos	7.5	https://www.youtube.com/watch?v=jzC0c-GWeDQ
56	Titanic	https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSqJPTUUxybY2fILEB6wzW_bZN8-OwY5FIvLA&s	1997	Romance y Drama.	195	Jack es un joven artista que gana un pasaje para viajar a América en el Titanic, el transatlántico más grande y seguro jamás construido. A bordo del buque conoce a Rose, una chica de clase alta que viaja con su madre y su prometido Cal, un millonario engreído a quien solo interesa el prestigio de la familia de su prometida. Jack y Rose se enamoran a pesar de las trabas que ponen la madre de ella y Cal en su relación. Mientras, el lujoso transatlántico se acerca a un inmenso iceberg.	James Cameron	Leonardo DiCaprio, Kate Winslet, Billy Zane, Gloria Stuart, Bill Paxton, Kathy Bates, Frances Fisher, Victor Garber, Bernard Hill, Jonathan Hyde, David Warner, Bernard Fox, Danny Nucci y Ioan Gruffudd.	20th Century Fox	Estados Unidos	6.8	https://www.youtube.com/watch?v=tA_qMdzvCvk
57	Forest Gump	https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTcp2IxZC1XOBPtu1KOifG2FKyu83jD1JsKBQ&s	1994	Comedia y Drama.	142	Sentado en un banco en Savannah, Georgia, Forrest Gump espera al autobús. Mientras éste tarda en llegar, el joven cuenta su vida a las personas que se sientan a esperar con él. Aunque sufre un pequeño retraso mental, esto no le impide hacer cosas maravillosas. Sin entender del todo lo que sucede a su alrededor, Forrest toma partido en los eventos más importantes de la historia de los Estados Unidos.	Robert Zemeckis	Tom Hanks, Robin Wright, Gary Sinise, Mykelti Williamson, Sally Field y Michael Conner Humphreys.	Paramount Pictures	Estados Unidos	8.2	https://www.youtube.com/watch?v=GIs2gpWpBiQ
58	Rescatando al soldado Ryan	https://pics.filmaffinity.com/Salvar_al_soldado_Ryan-442865234-large.jpg	1998	Bélico, Drama, Aventura, Cine belico y Épica.	169	Después de desembarcar en Normandía, en plena Segunda Guerra Mundial, unos soldados norteamericanos deben arriesgar sus vidas para salvar al soldado James Ryan, cuyos tres hermanos han muerto en la guerra.	Steven Spielberg	Tom Hanks, Tom Sizemore, Edward Burns, Matt Damon, Jeremy Davies, Adam Goldberg, Barry Pepper, Giovanni Ribisi y Vin Diesel.	Paramount Pictures y DreamWorks Pictures	Estados Unidos	7.8	https://www.youtube.com/watch?v=TAyhMtyup3o
59	American Psycho	https://es.web.img3.acsta.net/medias/nmedia/18/67/08/57/18971592.gif	2000	Terror, Thriller y Humor negro.	101	En la década de 1980, Patrick Bateman es un hombre exitoso y obsesionado por la competencia y por la perfección material, quien utiliza los más caros cosméticos masculinos, equipos de gimnasia, solárium y demás maquinaria estética para lograr un cuerpo atlético y bien acicalado, identificador material del éxito social.	Mary Harron	Christian Bale, Willem Dafoe, Jared Leto, Josh Lucas, Samantha Mathis, Matt Ross, Bill Sage, Chloë Sevigny, Cara Seymour, Justin Theroux, Guinevere Turner y Reese Witherspoon.	Lions Gate Films	Estados Unidos	6.6	https://www.youtube.com/watch?v=d1QmQsRD9_w
60	Karate Kid	https://play-lh.googleusercontent.com/whQVK8VDCyGWVBiWbxvzb9e00rifM4XfoKNq8Sag0FAABdFwzBQvGMyJmkDnOo2ne5IO	1984	Accion y Artes marciales.	126	Daniel Larusso llega a Los Ángeles de la costa este y enfrenta la difícil tarea de hacer nuevos amigos. Sin embargo, se convierte en el blanco del acoso de los Cobras, una amenazadora pandilla de estudiantes de karate, cuando inicia una relación con Ali, la ex novia del líder de los Cobras. Deseoso de defenderse e impresionar a su nueva novia, pero temeroso de enfrentar a la peligrosa pandilla, Daniel le pide a su conserje Miyagi, un maestro de las artes marciales, que le enseñe karate.	John G. Avildsen	Ralph Macchio, Noriyuki "Pat" Morita, Elisabeth Shue, William Zabka, Randee Heller y Cayetano Damian Badaracco.	Columbia Pictures	Estados Unidos	6.1	https://www.youtube.com/watch?v=xlnm0NtPoVs
61	Karate Kid Parte 2	https://perdidaenmismundos.files.wordpress.com/2020/11/karate-kid-2-750.jpg?w=421	1986	Accion, Drama y Artes marciales.	113	Daniel acompaña a Miyagi a su tierra, Okinawa, y allí aprende cosas sobre el pasado secreto de su maestro. Para Miyagi, es la oportunidad de ver a su padre por última vez y de reanudar su romance con el amor de su infancia. Sin embargo, su regreso también reavivará su vieja enemistad con Sato y arrastrará a Daniel a un choque de culturas y combates donde el precio del honor es la propia vida.	John G. Avildsen	Ralph Macchio, Noriyuki  Morita, Danny Kamekona, Nobu McCarthy, Yuji Okumoto, Tamlyn Tomita y Martin Kove.	Columbia Pictures y Sony	Estados Unidos	4.9	https://www.youtube.com/watch?v=V-T0ajeo7xQ
62	Karate Kid Parte 3	https://musicart.xboxlive.com/7/799b1100-0000-0000-0000-000000000002/504/image.jpg?w=1920&h=1080	1989	Accion, Drama y Artes marciales.	112	Daniel regresa de Okinawa con la esperanza de poder llevar una pacífica vida trabajando con su tutor Miyagi en su tienda de bonsáis. Sin embargo, la tranquilidad se ve truncada cuando es chantajeado para que compita contra Mike Barnes. Su maestro se niega a ayudarlo, así que el joven se busca otro entrenador, que resulta ser un hombre violento que sólo quiere formarlo para matar. Cuando Daniel se da cuenta de su error, intenta volver con Miyagi.	John G. Avildsen	Ralph Macchio, Noriyuki Morita, Robyn Lively, Sean Kanan, Randee Heller, Thomas Ian, Griffith y Martin Kove.	Columbia Pictures y Sony	Estados Unidos	4.2	https://www.youtube.com/watch?v=42xkTso8krA
66	Matrix Recargado	https://m.media-amazon.com/images/M/MV5BODE0MzZhZTgtYzkwYi00YmI5LThlZWYtOWRmNWE5ODk0NzMxXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg	2003	Accion y Ciencia ficción.	138	250.000 centinelas del Ejército de las Máquinas se dirigen hacia la ciudad oculta de Sión, último enclave de supervivencia de los humanos. Morfeo, Trinity y Neo disponen de 72 horas hasta que las máquinas lleguen al santuario humano. Las hermanas Lilly y Lana Wachowski alcanzarán una repercusión inesperada.	Hermanas Wachowski	Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss, Hugo Weaving, Monica Bellucci, Randall Duk Kim y Jada Pinkett Smith.	Warner Bros. Pictures	Estados Unidos y Australia	6.4	https://www.youtube.com/watch?v=dvauYuYX4Jc
65	Matrix	https://i.pinimg.com/1200x/6d/2c/0b/6d2c0bb97c516125f196f08c34b0e14b.jpg	1999	Accion y Ciencia ficción.	136	El programador informático Thomas Anderson, más conocido en el mundo de los "hacker" como Neo, está en el punto de mira del temible agente Smith. Otros dos piratas informáticos, Trinity y Morfeo, se ponen en contacto con Neo para ayudarlo a escapar. Matrix te posee. Sigue al conejo blanco.	Hermanas Wachowski	Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss y Hugo Weaving.	Warner Bros. Pictures	Estados Unidos y Australia	7.9	https://www.youtube.com/watch?v=Pl_H2Lmjn6k
64	Karate Kid (2010)	https://play-lh.googleusercontent.com/Z_t3rQxsOr4UEDJpiMxfaTtWKR-20HhHKf7UXch3Fpt9q8PAxOykbH2rGeVxw73u9ZrL=w240-h480-rw	2010	Accion, Drama y Artes marciales.	140	Cuando la carrera profesional de su madre los lleva a China, Dre Parker, de 12 años, descubre que es un extraño en una tierra desconocida. A pesar de que él sabe un poco de karate, sus habilidades para pelear no son suficientes contra Cheng, el acosador de su escuela. Dre encuentra a un amigo en el Sr. Han, un empleado de mantenimiento que también es maestro de las artes marciales. El Sr. Han le enseña a Dre todo sobre kung fu con la esperanza de que venza a Cheng.	Harald Zwart	Jackie Chan, Jaden Smith y Taraji P. Henson.	Sony Pictures Home Entertainment	Estados Unidos, Canada y China	5.7	https://www.youtube.com/watch?v=Az-gd83z-JA
22	Star Wars: Episode V - The Empire Strikes Back	https://i.ebayimg.com/images/g/GDEAAOSwo3pWgLdG/s-l1600.jpg	1980	Accion, Aventura, Space opera, Blockbuster y Ciencia ficción.	124	Son tiempos adversos para la rebelión. Aunque la Estrella de la Muerte ha sido destruida, las tropas imperiales han hecho salir a las fuerzas rebeldes de sus bases ocultas y los persiguen a través de la galaxia. Tras escapar de la terrible Flota Imperial, un grupo de guerreros de la libertad, encabezados por Luke Skywalker, ha establecido una nueva base secreta en el remonto mundo helado de Hoth.	George Lucas	Mark Hamill, Harrison Ford, Carrie Fisher, Peter Cushing, Alec Guinness, Anthony Daniels, Kenny Baker, Peter Mayhew, David Prowse, Jack Purvis, Eddie Byrne y James Earl Jones.	Lucasfilm	Estados Unidos	8.1	https://www.youtube.com/watch?v=JNwNXF9Y6kY
71	El Padrino	https://es.web.img3.acsta.net/pictures/22/01/13/16/56/0142706.jpg	1972	Drama, Crimen y Gánsteres	177	Don Vito Corleone es el respetado y temido jefe de una de las cinco familias de la mafia de Nueva York en los años 40. El hombre tiene cuatro hijos: Connie, Sonny, Fredo y Michael, que no quiere saber nada de los negocios sucios de su padre. Cuando otro capo, Sollozzo, intenta asesinar a Corleone, empieza una cruenta lucha entre los distintos clanes.	Francis Ford Coppola	Marlon Brando, Al Pacino, Robert Duvall, James Caan, Richard Castellano y Diane Keaton.	Paramount Pictures	Estados Unidos	9.0	https://www.youtube.com/watch?v=iOyQx7MXaz0
63	Karate Kid 4: La Nueva Aventura	https://es.web.img3.acsta.net/r_1280_720/medias/nmedia/18/79/76/01/19516910.jpg	1994	Accion, Drama y Artes marciales.	108	Durante una conmemoración en honor a los soldados japoneses que lucharon durante la Segunda Guerra Mundial, el señor Miyagi conoce a Julie. La joven perdió a sus padres cuando solo era una niña y ahora, a sus 17 años, se convierte en el objetivo de Alpha Elite, un grupo de disciplina militar de su instituto al que deberá aprender a hacer frente. Por ello, Miyagi decide enseñarle unas lecciones de kárate.	Christopher Cain	Hilary Swank, Noriyuki Morita, Michael Ironside, Constance Towers y Chris Conrad	Columbia Pictures y Sony	Estados Unidos	3.5	https://www.youtube.com/watch?v=5LNE7jk2QWY
72	El padrino II	https://www.mubis.es/media/movies/400/26974/el-padrino-parte-ii-l_cover.jpg	1974	Drama, Crimen y Gánsteres	200	Tras la muerte de Don Vito Corleone, su hijo Michael es elegido para liderar los negocios familiares. El nuevo cabeza de familia debe lidiar con un panorama cambiante de amistades y enemistades, al tener que negociar con la mafia judía y perder el apoyo de Frankie. Al mismo tiempo, Michael escapa por los pelos de un atentado. Simultáneamente, se recuerda el ascenso y los orígenes de Don Vito en Sicilia y como inmigrante en Nueva York.	Francis Ford Coppola	Al Pacino, Robert Duvall, Diane Keaton, Robert De Niro, Talia Shire, Morgana King, John Cazale, Mariana Hill y Lee Strasberg.	Paramount Pictures	Estados Unidos	8.9	https://www.youtube.com/watch?v=Ts1lHOyWNSE
74	El padrino de Mario Puzo, epílogo: la muerte de Michael Corleone	https://i.blogs.es/653d70/el-padrino-3-epilogo-poster-trailer-opinion/450_1000.jpg	2020	Drama, Crimen y Gánsteres	162	Michael Corleone (Al Pacino) ya tiene 60 años, y solo quiere proteger a su familia del crimen que les rodea y encontrar al mejor sucesor para su emporio. Ese podría ser el vehemente Vincent (Andy García), pero también podría ser la chispa que convertiría la esperanza de Michael de tener una empresa legítima en un infierno de violencia.	Francis Ford Coppola	Al Pacino, Diane Keaton, Talia Shire, Andy García, Eli Wallach, Joe Mantegna, George Hamilton y Bridget Fonda.	Paramount Pictures	Estados Unidos	6.2	https://www.youtube.com/watch?v=JV59AdcpqEE
73	El padrino III	https://es.web.img3.acsta.net/medias/nmedia/18/68/09/69/20420487.jpg	1990	Drama, Crimen y Gánsteres	163	Michael Corleone, heredero del imperio de don Vito Corleone, intenta rehabilitarse socialmente y legitimizar todas las posesiones de la familia negociando con el Vaticano. Después de luchar toda su vida se encuentra cansado y centra todas sus esperanzas en encontrar a un sucesor que se haga cargo de los negocios.	Francis Ford Coppola	Al Pacino, Diane Keaton, Talia Shire y Andy García.	Paramount Pictures	Estados Unidos	7.8	https://www.youtube.com/watch?v=_LZJxPbzvOo
\.


--
-- Name: catalogo catalogo_pkey; Type: CONSTRAINT; Schema: public; Owner: joacoeze
--

ALTER TABLE ONLY public.catalogo
    ADD CONSTRAINT catalogo_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

